// Case: The Auction (The Gilded Cage). Once a month Marcus Vane, "the Curator", owner of the Gilded
// Cage, sells the city's secrets to the bidders in his velvet booths. Tonight's lot #1 is a tape of
// Supergirl from a night she doesn't remember. The trail: Vane sells (his photographer works the
// booths); Lionel Strand of StrandCorp is the top bidder (he wants a hero on a leash); the master
// goes to the StrandCorp heliport at 4 AM. The booths (Gilded Cage only) hold the bidders: peek
// behind a curtain (X-ray: unseen; by hand: someone notices).
// Same shape as squirt.js: keys "<room kind>:<object id>", `cat` for the owner's confrontation
// (deal = who sells, supply = who buys, drop = where the tape goes), `v3` = 3D club only.
import { CLIPS } from '../../club3d/clips.js';

export const AUCTION = {
  id: 'auction', title: 'The Auction', tagline: 'Tonight\'s lot #1 is you. Stop the sale.', theme: 'blackmail',
  club: 'The Gilded Cage', room: 'gilded', difficulty: 'normal',
  clips: { wall: [...CLIPS.shame, ...CLIPS.captive], trap: CLIPS.captive, shame: CLIPS.shame },
  events: ['redcarpet', 'paparazzi', 'raid', 'fight'],
  need: 8,
  rep: 30,
  booths: [
    { who: 'Gloria Sterling, editor of the Daily Scoop', clue: 'booth:1', line: '"Fifty thousand for the Supergirl tape. My front page needs her."' },
    { who: 'Big Tony Marchetti and two bodyguards', clue: 'booth:2', line: '"If Strand wants her that bad, let him pay. I want the heliport schedule."' },
    { who: 'Lionel Strand, CEO of StrandCorp', clue: 'booth:3', line: '"Whatever they bid, double it. I want her on a leash by morning."' },
    { who: 'The Curator\'s photographer, loading film', clue: 'booth:4', line: '"Boss says get her on film again tonight. Fresh copies for the winner."' },
  ],
  clues: {
    'booth:1': { v3: true, flavour: true, note: 'Booth 1: the Daily Scoop is bidding for her tape',
      text: 'Booth 1: <b>Gloria Sterling</b> of the Daily Scoop, a bidding paddle in her lap. "Fifty thousand for the Supergirl tape."' },
    'booth:2': { v3: true, cat: 'drop', note: 'Booth 2: Marchetti wants the heliport schedule',
      text: 'Booth 2: <b>Big Tony Marchetti</b>. "If Strand wants her that bad, let him pay. I want the <b>heliport</b> schedule."' },
    'booth:3': { v3: true, cat: 'supply', note: 'Booth 3: Lionel Strand is the top bidder',
      text: 'Booth 3: <b>Lionel Strand</b>, StrandCorp. "Whatever they bid, double it. I want her on a leash by morning."' },
    'booth:4': { v3: true, cat: 'deal', note: 'Booth 4: Vane\'s photographer, shooting fresh copies',
      text: 'Booth 4: a photographer loading film. "Boss says get her on film again tonight. <b>Vane</b> wants fresh copies for the winner."' },

    'bar:glass': { drink: true, flavour: true, note: 'The "Gilded" cocktail has gold leaf and a kick',
      text: 'A champagne cocktail with gold leaf floating on top. The bartender calls it a <b>Gilded</b>. It smells faintly of almonds.' },
    'bar:napkin': { cat: 'deal', note: 'Napkin: "Lot 1: S.G. Reserve 2M. — C."',
      text: 'A napkin in neat copperplate: <b>"Lot 1: S.G. Reserve two million. — C."</b>' },
    'bar:pills': { cat: 'deal', note: 'Sleeping pills behind the bar',
      text: 'A bottle of crushed sleeping pills behind the bar. The Gilded makes the night disappear.' },
    'bar:coaster': { item: 'VIP wristband', flavour: true, note: 'A VIP wristband under a coaster',
      text: 'Something stiff under the coaster: a <b>VIP wristband</b>, gold mesh.' },
    'bar:phone': { cat: 'drop', note: 'Text: "Heliport. 4AM. Master tape, no copies."',
      text: 'A phone, face down, buzzing: <b>"StrandCorp heliport. 4 AM. The master, no copies."</b>' },
    'bar:jar': { flavour: true, note: 'The tip jar is stuffed with auction paddles',
      text: 'The tip jar is stuffed with numbered bidding paddles. Somebody\'s been bidding all night.' },

    'entrance:tickets': { flavour: true, note: 'Coat tickets marked "BIDDER"',
      text: 'Claim tickets with <b>BIDDER</b> stamped on the back, each with a booth number.' },
    'entrance:jacket': { cat: 'supply', note: 'A StrandCorp keycard in a cashmere coat',
      text: 'A cashmere coat. In the pocket: a <b>StrandCorp</b> executive keycard, "L. STRAND".' },
    'entrance:list': { cat: 'deal', note: 'Guest list: "The Curator\'s auction: bidders only"',
      text: 'The guest list: <b>"Tonight: the Curator\'s auction. Bidders only. Lot 1 at midnight."</b>' },
    'entrance:mints': { flavour: true, note: 'Gold-wrapped mints',
      text: 'A bowl of mints in gold foil. Everything in here is gold.' },
    'entrance:band': { item: 'VIP wristband', flavour: true, note: 'A spare VIP wristband',
      text: 'A spare <b>VIP wristband</b>, left on the counter.' },

    'main:phone': { cat: 'deal', note: 'The DJ\'s phone: "Play the tape on the screens at midnight"',
      text: 'The DJ\'s phone: <b>"Curator says roll the preview on every screen at midnight. Let the bidders see what they\'re buying."</b>' },
    'main:setlist': { flavour: true, note: 'Set list: "12:00 LOT ONE (lights down)"',
      text: 'The set list. At midnight, in gold pen: <b>"LOT ONE (lights down)"</b>.' },
    'main:vial': { drink: true, flavour: true, note: 'A vial of the Gilded\'s secret ingredient',
      text: 'A little vial tucked behind the mixer: whatever goes in the Gilded, neat.' },
    'main:mixer': { flavour: true, note: 'A video feed wired from the office to the screens',
      text: 'A video cable runs from the mixer to the screens, labelled <b>"OFFICE FEED"</b>.' },
    'main:headphones': { flavour: true, note: 'The DJ\'s headphones, gold-plated',
      text: 'Gold-plated headphones. Of course.' },

    'vip:tray': { flavour: true, note: 'A silver tray of numbered paddles',
      text: 'A silver tray of numbered bidding paddles. Four are missing: the four booths.' },
    'vip:glass': { flavour: true, note: 'A half-finished Gilded',
      text: 'A half-finished Gilded. Its drinker is asleep on the couch.' },
    'vip:card': { cat: 'supply', note: 'Card: "Lionel Strand, StrandCorp. Bid: unlimited."',
      text: 'A heavy card on the table: <b>Lionel Strand · StrandCorp</b>. Written on it: "Bid: unlimited."' },
    'vip:watch': { flavour: true, note: 'A watch stopped at midnight',
      text: 'A watch left on the couch, stopped at midnight.' },
    'vip:matches': { cat: 'drop', note: 'Matchbook: "StrandCorp Tower · Helipad"',
      text: 'A matchbook from <b>StrandCorp Tower</b>. Inside the cover: <b>"Helipad. 4."</b>' },
    'vip:bucket': { flavour: true, note: 'Champagne on ice, untouched',
      text: 'Champagne on ice, untouched. Bidders keep their heads clear.' },

    'restroom:mirror': { flavour: true, note: 'A camera lens behind the mirror',
      text: 'The mirror is two-way: behind it, a <b>camera</b>. The Curator collects everything.' },
    'restroom:pills': { cat: 'deal', note: 'The Gilded\'s knockout powder, bagged',
      text: 'A bag of white powder hidden behind the cistern: the Gilded\'s knockout. Bagged.' },
    'restroom:towels': { flavour: true, note: 'A hollow behind the towel holder',
      text: 'A hollow behind the towel holder. Empty film canisters.' },
    'restroom:receipt': { cat: 'supply', note: 'Receipt: a deposit "on account, StrandCorp"',
      text: 'A crumpled receipt for a two-hundred-thousand deposit, <b>"on account: StrandCorp"</b>.' },
    'restroom:soap': { flavour: true, note: 'Someone wrote "DON\'T DRINK THE GOLD"',
      text: 'Someone wrote on the mirror in soap: <b>"DON\'T DRINK THE GOLD."</b>' },

    'office:ledger': { cat: 'deal', note: 'Ledger: "Lots sold", every one a secret, signed "C."',
      text: 'The ledger: a page for every lot ever sold, every one somebody\'s secret, every page signed <b>"C."</b> for Curator.' },
    'office:cash': { cat: 'drop', note: 'Envelope: "HELIPAD · 4AM · BALANCE ON DELIVERY"',
      text: 'An envelope of cash marked <b>"HELIPAD · 4AM · BALANCE ON DELIVERY"</b>.' },
    'office:phone': { cat: 'supply', note: 'Strand on the burner: "Name your price."',
      text: 'A burner phone. One contact: <b>L.S.</b> Last message: "Name your price. I want the only copy."' },
    'office:key': { item: 'cellar key', flavour: true, note: 'The vault key',
      text: 'A key on a gold tag: <b>VAULT</b>. You take it.' },
    'office:photo': { cat: 'deal', note: 'Photo: Vane at his first auction, "The Curator"',
      text: 'A framed photo: Marcus Vane at a lectern, gavel raised. Engraved: <b>"The Curator. Est. 2019."</b>' },
    'office:monitor': { flavour: true, note: 'CCTV: every booth, every bidder',
      text: 'The CCTV shows every booth from above. The Curator watches his bidders bid.' },

    'talk:waiters': { v3: true, cat: 'deal', note: 'Overheard: the Curator sells lot one at midnight',
      text: '"Lot one\'s at midnight." "The Supergirl thing?" "The Curator says it\'s the biggest sale he\'s ever had."' },
    'talk:suits': { v3: true, cat: 'supply', note: 'Overheard: Strand will outbid everyone',
      text: '"Strand\'s bidding personally." "Then it\'s over. Nobody outbids StrandCorp."' },
    'talk:bouncers': { v3: true, cat: 'drop', note: 'Overheard: the master goes to the heliport at four',
      text: '"Courier takes the master up to the heliport at four." "StrandCorp\'s?" "Whose else has a heliport?"' },
    'vip:host': { v3: true, cat: 'deal', note: 'Celeste bragged: the Curator has a tape of Supergirl',
      text: 'Celeste, pleased with herself: <b>"Marcus has a tape of her. Supergirl. A night she doesn\'t remember. He\'s been saving it."</b>' },
    'alley:bag': { v3: true, cat: 'drop', note: 'The courier\'s case: "MASTER · HELIPAD 4AM"',
      text: 'The courier\'s steel case: a single tape, labelled <b>"MASTER · HELIPAD · 4AM"</b>.' },
    'restroom:deal': { v3: true, cat: 'deal', note: 'The stall: the photographer swapping film',
      text: 'The man in the last stall was swapping rolls of film. "Fresh copies for the Curator. He wants her on film again tonight."' },
    'storage:stash': { v3: true, cat: 'deal', note: 'Behind the crates: the Curator\'s archive',
      text: 'Behind the crates: boxes of tapes and negatives, every box labelled with a name. One box says <b>SUPERGIRL</b>.' },
    'bar:spiked': { v3: true, cat: 'deal', note: 'X-ray: the Gilded is laced with a sedative',
      text: 'X-ray shows a sediment under the gold leaf: a sedative. The Gilded is how the Curator gets his material.' },
    'uv:wall': { v3: true, cat: 'drop', note: 'UV writing: "HELIPAD 4AM"',
      text: 'Under the glow the wall is covered in UV marker: the stock code, and <b>"HELIPAD 4AM"</b>.' },
    'boss:confession': { v3: true, cat: 'drop', note: 'Marcus Vane confessed: he sells it, Strand buys it, the heliport at 4 AM',
      text: 'The Curator folds: he sells the tape, Lionel Strand has bought it, and the master goes to the StrandCorp heliport at 4 AM.' },
  },
  solvedText: 'Marcus Vane, the Curator, sells the tape, Lionel Strand of StrandCorp is buying it, and the master goes to the StrandCorp heliport at 4 AM.',
  drugName: 'The Gilded', uvLine: 'HELIPAD 4AM',
  carrierLine: 'A roll of film in his pocket: he\'s the Curator\'s.',
  talks: [
    { id: 'waiters', who: 'Two waiters', clue: 'talk:waiters' },
    { id: 'suits', who: 'Two men in suits', clue: 'talk:suits' },
    { id: 'bouncers', who: 'Two bouncers', clue: 'talk:bouncers' },
  ],
  rumours: [
    { id: 'curator', text: 'Only the Curator\'s guests get past the VIP rope.', teach: 'who' },
    { id: 'lot', text: 'Lot one\'s at midnight. Everyone\'s here for lot one.', teach: 'lot' },
    { id: 'gold', text: 'Never drink the gold. Just ask the people in the booths.', teach: 'gold' },
    { id: 'tape', text: 'They say there\'s a tape of Supergirl. Here. Tonight.' },
    { id: 'booths', text: 'The booths are for bidders. Don\'t open the curtains.' },
    { id: 'drop', text: 'At the drop the bouncers can\'t see a thing.' },
    { id: 'cams', text: 'The Curator films every booth.' },
    { id: 'alley', text: 'There\'s a courier out back with a steel case.' },
  ],
  whispers: [
    { id: 'pass', text: 'Tell Celeste the Curator invited you.', teach: 'who' },
    { id: 'bid', text: 'Booth three just bid two million. For her.' },
    { id: 'code', text: 'Office code\'s {CODE}. Vane never changes it.', code: true },
    { id: 'stash', text: 'The archive\'s in the stock room, behind the crates.' },
  ],
  vip: {
    host: 'Celeste',
    intro: '"Welcome to the gallery, darling. Everything up here is for sale. Even you."',
    questions: [
      { id: 'who', q: '"Who invited you?"', answer: 'curator',
        options: [{ label: '"Lionel Strand."', value: 'strand' }, { label: '"The Curator."', value: 'curator' }, { label: '"Nobody."', value: 'none' }, { label: '"The DJ."', value: 'dj' }] },
      { id: 'lot', q: '"Here for which lot?"', answer: 'one',
        options: [{ label: '"Whatever\'s cheapest."', value: 'cheap' }, { label: '"Lot one."', value: 'one' }, { label: '"I\'m just dancing."', value: 'none' }, { label: '"The last one."', value: 'last' }] },
      { id: 'gold', q: 'She offers a Gilded. "Drink?"', answer: 'never',
        options: [{ label: '"Don\'t mind if I do."', value: 'yes' }, { label: '"Never the gold."', value: 'never' }, { label: '"Water."', value: 'water' }, { label: '"Later."', value: 'later' }] },
    ],
    win: 'vip:host',
  },
  boss: {
    name: 'Marcus Vane',
    steps: [
      { cat: 'deal', line: '"I host parties, hero. People bring their own secrets."' },
      { cat: 'supply', line: '"And who would pay for a tape of you? Be serious."' },
      { cat: 'drop', line: '"Even if you\'re right, by four o\'clock it\'s out of my hands."' },
    ],
    confession: 'boss:confession',
  },
  questions: [
    { q: 'Who is selling the tape?', answer: 'vane',
      options: [{ label: 'The photographer', value: 'photo' }, { label: 'Celeste', value: 'celeste' }, { label: 'Marcus Vane, the Curator', value: 'vane' }, { label: 'Gloria Sterling', value: 'gloria' }] },
    { q: 'Who is buying it?', answer: 'strand',
      options: [{ label: 'Lionel Strand, StrandCorp', value: 'strand' }, { label: 'Big Tony Marchetti', value: 'tony' }, { label: 'The Daily Scoop', value: 'scoop' }, { label: 'The police', value: 'police' }] },
    { q: 'Where does the master tape go?', answer: 'heli',
      options: [{ label: 'The newspaper office', value: 'paper' }, { label: 'StrandCorp\'s heliport, 4 AM', value: 'heli' }, { label: 'The club\'s vault', value: 'vault' }, { label: 'The docks, Friday', value: 'docks' }] },
  ],
  leads: [
    { id: 'auction-heli', name: 'The handover: StrandCorp heliport', kind: 'special', venue: 'Penthouse', theme: 'blackmail', reward: 120,
      by: ['bar:phone', 'office:cash', 'vip:matches', 'uv:wall', 'alley:bag', 'booth:2'],
      blurb: 'The master tape goes to the StrandCorp heliport at 4 AM. Get it back before Strand does.' },
    { id: 'auction-archive', name: 'The Curator\'s archive', kind: 'special', venue: 'High-Roller Suite', theme: 'blackmail', reward: 100,
      by: ['storage:stash', 'office:ledger', 'restroom:mirror', 'booth:4'],
      blurb: 'Every secret the Curator ever sold is in his archive. Burn it.' },
    { id: 'auction-scoop', name: 'The Daily Scoop\'s presses', kind: 'street', reward: 80,
      by: ['booth:1', 'entrance:list'],
      blurb: 'The Scoop has a front page ready with your face on it. Stop the presses.' },
  ],
};
