// Case: The Polaroid Racket. City councillors are being photographed, drugged and sloppy, in the
// club's VIP, and blackmailed with the pictures. The trail: Vivian "Flash" Cole, the VIP hostess,
// takes them (hidden cameras, knockout cocktails); Dutch Varga, a developer who wants city
// contracts, pays for them; Lenny Gold, the owner, launders it; the negatives change hands Friday
// in the High-Roller Suite. (Fitting: the owner keeps an envelope of polaroids on her too.)
// Same shape as squirt.js: keys "<room kind>:<object id>", `cat` for the 3D club's blackmail
// exchange (deal = who shoots them, supply = who pays, drop = the payoff), `v3` = 3D club only.

export const BLACKMAIL = {
  id: 'blackmail', title: 'The Polaroid Racket', tagline: 'Find out who is blackmailing the city\'s councillors', theme: 'blackmail',
  need: 8,
  rep: 25,
  clues: {
    'bar:glass': { drink: true, flavour: true, note: 'The VIP\'s "blue cocktail" is spiked',
      text: 'A blue cocktail nobody ordered, fizzing. The bartender says the VIP drinks nothing else. It smells of something sweet and chemical: <b>knockout drops</b>.' },
    'bar:napkin': { cat: 'supply', note: 'Napkin: "D.V. Friday. Suite 7."',
      text: 'A napkin with a phone number crossed out and, underneath: <b>"D.V. Friday. Suite 7."</b>' },
    'bar:pills': { cat: 'deal', note: 'Knockout pills behind the bar',
      text: 'A bag of chalky blue pills: knockout drops, crushed into the VIP\'s cocktails. Sloppy guests make good photographs.' },
    'bar:coaster': { item: 'VIP wristband', flavour: true, note: 'A VIP wristband under a coaster',
      text: 'Something stiff under the coaster: a <b>VIP wristband</b>.' },
    'bar:phone': { cat: 'drop', note: 'Text: "Payoff Friday. High-Roller Suite. Bring the negatives."',
      text: 'A phone, face down, still buzzing: <b>"Payoff Friday. High-Roller Suite. Bring the negatives."</b>' },
    'bar:jar': { flavour: true, note: 'The tip jar is stuffed with fifties',
      text: 'The tip jar is stuffed with fifties. Somebody is paying for a lot of silence.' },

    'entrance:tickets': { flavour: true, note: 'Coat tickets for "Booth 3" guests, all councillors',
      text: 'Claim tickets with "BOOTH 3" pencilled on the back. Every one of them belongs to someone from city hall.' },
    'entrance:jacket': { cat: 'supply', note: 'A business card: Varga Developments',
      text: 'An expensive jacket. In the pocket, a business card: <b>Dutch Varga · Varga Developments</b>. On the back: "For services rendered."' },
    'entrance:list': { cat: 'deal', note: 'Guest list: councillors ticked in red, "FLASH" beside them',
      text: 'The guest list. Four names ticked in red, all councillors. Beside each one, in the same hand: <b>"FLASH"</b>.' },
    'entrance:mints': { flavour: true, note: 'Blue mints that aren\'t mints',
      text: 'A bowl of mints. The blue ones are chalky and bitter: the same knockout drops, pressed into candy.' },
    'entrance:band': { item: 'VIP wristband', flavour: true, note: 'A spare VIP wristband',
      text: 'A spare <b>VIP wristband</b>, left on the counter.' },

    'main:phone': { cat: 'deal', note: 'Text from Flash: "Lights low at 1 AM. Booth 3."',
      text: 'The DJ\'s phone: <b>"Lights low at 1 AM. Councillor\'s in booth 3. — Flash"</b>' },
    'main:setlist': { flavour: true, note: 'The DJ dims the lights at 1 AM for "the VIP"',
      text: 'The set list. At 1 AM, in red: "LIGHTS DOWN (VIP)". Somebody wants the dark.' },
    'main:vial': { drink: true, flavour: true, note: 'A vial of the knockout drops',
      text: 'A little blue vial tucked behind the mixer. The knockout drops, neat.' },
    'main:mixer': { flavour: true, note: 'A remote shutter release taped under the mixer',
      text: 'Taped under the mixer: a remote shutter release. A wire runs off toward the VIP.' },
    'main:headphones': { flavour: true, note: 'Headphones, nothing more',
      text: 'Headphones. The DJ\'s, by the smell of them. Nothing hidden here.' },

    'vip:tray': { cat: 'deal', note: 'A camera lens hidden in the tray\'s centrepiece',
      text: 'The silver centrepiece on the tray has a tiny glass eye in it: <b>a hidden camera</b>, pointed at the couch.' },
    'vip:glass': { flavour: true, note: 'A councillor\'s glass, still blue',
      text: 'A glass with a blue residue and a city hall pin beside it. Someone left in no state to take their pin.' },
    'vip:card': { cat: 'supply', note: 'Varga Developments: "For services rendered"',
      text: 'A business card on the table: <b>Varga Developments</b>. On the back, in a different hand: "Booth 3. Thank you."' },
    'vip:watch': { flavour: true, note: 'A councillor\'s engraved watch',
      text: 'An engraved watch: "To Councillor Price, for twenty years of service." Left behind.' },
    'vip:matches': { cat: 'drop', note: 'High-Roller Suite matchbook: "FRI" inside',
      text: 'A matchbook from the <b>High-Roller Suite</b>. Written inside the cover: <b>"FRI"</b>.' },
    'vip:bucket': { flavour: true, note: 'The champagne is for show',
      text: 'The champagne is warm and untouched. Nobody here drinks it: the blue cocktails are the point.' },

    'restroom:mirror': { cat: 'deal', note: 'A two-way mirror, a camera behind it',
      text: 'The mirror is cold glass over a dark space. Through it, faintly: <b>a camera on a tripod</b>. Two-way mirror.' },
    'restroom:pills': { cat: 'deal', note: 'Knockout pills behind the towels',
      text: 'A bag of chalky blue pills stuck behind the towel holder. The knockout drops, restocked.' },
    'restroom:towels': { flavour: true, note: 'A hollow behind the towel holder',
      text: 'The towel holder\'s cover is loose. A hollow space behind it.' },
    'restroom:receipt': { cat: 'supply', note: 'Photo lab receipt: 40 prints, paid by Varga',
      text: 'A crumpled receipt from a photo lab on Fifth: 40 prints, rush job, paid by <b>Varga Developments</b>.' },
    'restroom:soap': { flavour: true, note: 'Fixer chemical on the sink',
      text: 'The sink smells of vinegar: photographic fixer. Somebody developed film in here.' },

    'office:ledger': { cat: 'supply', note: 'Ledger: payments from "D.V." every month',
      text: 'The ledger: a column of payments in from <b>"D.V."</b>, every month, far bigger than the bar takings.' },
    'office:cash': { cat: 'drop', note: 'An envelope of cash: "FRI · SUITE"',
      text: 'A fat envelope of cash, marked <b>"FRI · SUITE"</b>.' },
    'office:phone': { cat: 'supply', note: 'Varga on the burner: "Friday. All of them."',
      text: 'A burner phone. One contact: <b>D.V.</b> Last message: "Friday. All of them. Negatives too."' },
    'office:key': { item: 'cellar key', flavour: true, note: 'The cellar key',
      text: 'A key on a red tag: <b>CELLAR</b>. You take it.' },
    'office:photo': { cat: 'deal', note: 'Polaroids of councillors, signed "Flash"',
      text: 'A drawer of polaroids: councillors, sloppy and blue-lipped, on the VIP couch. Every one is signed on the back: <b>"Flash"</b>.' },
    'office:monitor': { flavour: true, note: 'The CCTV shows the VIP\'s couch, close up',
      text: 'One CCTV feed shows nothing but the VIP couch, close up. That\'s not security.' },

    // the 3D club's own sources (v3)
    'talk:hostess': { v3: true, cat: 'deal', note: 'Overheard: Flash wants councillors in booth 3 by one, lights low',
      text: '"Flash wants every councillor in booth 3 by one." "Lights low, blue cocktails, smile for the camera."' },
    'talk:aides': { v3: true, cat: 'supply', note: 'Overheard: "Pay what Varga asks. Friday."',
      text: '"If those pictures get out, my boss is finished." "Then pay what Varga asks. Friday."' },
    'talk:bouncers': { v3: true, cat: 'drop', note: 'Overheard: the courier takes the envelopes out back at two',
      text: '"Courier takes the envelopes out the back at two." "Lenny counts the money himself. Friday it\'s the big one."' },
    'vip:host': { v3: true, cat: 'supply', note: 'Flash bragged: Varga pays double for councillors',
      text: 'Flash, three cocktails in, can\'t help herself: <b>"Dutch pays double for councillors. Friday, the suite, I hand over the whole set."</b>' },
    'alley:bag': { v3: true, cat: 'drop', note: 'The courier\'s bag: envelopes of prints for city hall',
      text: 'The courier\'s bag: envelopes of prints, each addressed to someone at city hall, each with a price written on it.' },
    'restroom:deal': { v3: true, cat: 'deal', note: 'The stall: a man swapping film canisters',
      text: 'The man in the last stall was swapping film canisters with a bouncer. The labels: "BOOTH 3 · TUE".' },
    'storage:stash': { v3: true, cat: 'deal', note: 'Boxes of prints and negatives behind the beer',
      text: 'Behind the beer crates: boxes of prints and negatives, sorted by name. Half of city hall is in here.' },
    'bar:spiked': { v3: true, cat: 'deal', note: 'The blue cocktail is spiked with knockout drops',
      text: 'X-ray shows a cloud of chalky powder settling in the blue cocktail. The VIP\'s drink of choice is spiked.' },
    'uv:wall': { v3: true, cat: 'drop', note: 'UV writing: "SUITE 7 · FRI · VARGA"',
      text: 'Under the drug-vision glow the wall is covered in UV marker: the stock code, and <b>"SUITE 7 · FRI · VARGA"</b>.' },
    'boss:confession': { v3: true, cat: 'drop', note: 'Lenny Gold confessed: Flash shoots them, Varga pays, Friday at the suite',
      text: 'Lenny folds: Flash shoots them, Dutch Varga pays for them, and the negatives change hands Friday in the High-Roller Suite.' },
  },
  solvedText: 'Flash takes the pictures, Dutch Varga pays for them, and the negatives change hands Friday at the High-Roller Suite.',
  drugName: 'The blue drops', uvLine: 'SUITE 7 FRI VARGA',
  carrierLine: 'Blue knockout drops: the VIP\'s supply, sold on the floor too.',
  talks: [
    { id: 'hostess', who: 'Two hostesses', clue: 'talk:hostess' },
    { id: 'aides', who: 'Two councillors\' aides', clue: 'talk:aides' },
    { id: 'bouncers', who: 'Two bouncers', clue: 'talk:bouncers' },
  ],
  rumours: [
    { id: 'dutch', text: 'Only Dutch Varga\'s friends get past the VIP rope tonight.', teach: 'who' },
    { id: 'blue', text: 'Up in VIP they only drink the blue cocktail. Flash insists.', teach: 'drink' },
    { id: 'camera', text: 'Never say no to Flash\'s camera. She\'ll have you thrown out.', teach: 'camera' },
    { id: 'mirror', text: 'The restroom mirror is weird. Like it\'s watching you.' },
    { id: 'councillor', text: 'Saw a councillor carried out of VIP last week. Out cold.' },
    { id: 'swap', text: 'Bouncers lose it at the drop. Staff door\'s wide open for a beat.' },
    { id: 'cams', text: 'Lenny\'s got a camera in every room. Even the restroom.' },
    { id: 'alley', text: 'A courier takes envelopes out the back every night.' },
  ],
  whispers: [
    { id: 'pass', text: 'Tell Flash that Dutch sent you. Works every time.', teach: 'who' },
    { id: 'fri', text: 'Friday. The suite. Dutch pays cash for the whole set.' },
    { id: 'code', text: 'Office code\'s {CODE}. Lenny never changes it.', code: true },
    { id: 'stash', text: 'The negatives are in the stock room, behind the beer.' },
  ],
  vip: {
    host: 'Vivian "Flash" Cole',
    intro: '"Hey there. Nobody comes up here unless I like them. Let\'s see if I like you."',
    questions: [
      { id: 'who', q: '"Who invited you up?"', answer: 'varga',
        options: [{ label: '"Lenny did."', value: 'lenny' }, { label: '"Dutch Varga."', value: 'varga' }, { label: '"The DJ."', value: 'dj' }, { label: '"Nobody. I just walked in."', value: 'none' }] },
      { id: 'drink', q: '"What are you drinking, sweetie?"', answer: 'blue',
        options: [{ label: '"Champagne."', value: 'champ' }, { label: '"The blue one."', value: 'blue' }, { label: '"Just water."', value: 'water' }, { label: '"Whatever\'s free."', value: 'free' }] },
      { id: 'camera', q: 'She lifts a camera. "Mind if I take your picture?"', answer: 'ahead',
        options: [{ label: '"No photos!"', value: 'no' }, { label: '"Only my good side."', value: 'side' }, { label: '"Go ahead. I love the camera."', value: 'ahead' }, { label: '"Delete it after."', value: 'delete' }] },
    ],
    win: 'vip:host',
  },
  boss: {
    name: 'Lenny Gold',
    steps: [
      { cat: 'deal', line: '"Photos? People take photos in clubs, hero. That\'s not a crime."' },
      { cat: 'supply', line: '"And who would pay good money for pictures of a few drunk councillors?"' },
      { cat: 'drop', line: '"You\'ll never get your hands on the negatives anyway."' },
    ],
    confession: 'boss:confession',
  },
  questions: [
    { q: 'Who is taking the photographs?', answer: 'flash',
      options: [{ label: 'The DJ', value: 'dj' }, { label: 'Vivian "Flash" Cole, the VIP hostess', value: 'flash' }, { label: 'The bartender', value: 'bar' }, { label: 'A councillor', value: 'councillor' }] },
    { q: 'Who is paying for them?', answer: 'varga',
      options: [{ label: 'Lenny Gold', value: 'lenny' }, { label: 'The Daily Scoop', value: 'paper' }, { label: 'Dutch Varga, the developer', value: 'varga' }, { label: 'The police', value: 'police' }] },
    { q: 'When and where do the negatives change hands?', answer: 'suite',
      options: [{ label: 'Thursday, Pier 9', value: 'pier' }, { label: 'Tonight, in the alley', value: 'alley' }, { label: 'Monday, city hall', value: 'hall' }, { label: 'Friday, the High-Roller Suite', value: 'suite' }] },
  ],
  leads: [
    { id: 'blackmail-suite', name: 'The payoff: High-Roller Suite', kind: 'special', venue: 'High-Roller Suite', theme: 'blackmail', reward: 120,
      by: ['bar:phone', 'office:cash', 'vip:matches', 'uv:wall', 'bar:napkin'],
      blurb: 'The negatives change hands Friday in the High-Roller Suite. Be there first.' },
    { id: 'blackmail-varga', name: 'Varga Developments penthouse', kind: 'special', venue: 'Penthouse', theme: 'blackmail', reward: 100,
      by: ['entrance:jacket', 'vip:card', 'office:phone', 'office:ledger', 'restroom:receipt'],
      blurb: 'Dutch Varga pays for the pictures. His penthouse is full of them. Raid it.' },
    { id: 'blackmail-lab', name: 'The photo lab on Fifth', kind: 'street', reward: 80,
      by: ['restroom:receipt', 'restroom:soap'],
      blurb: 'Flash\'s prints come out of a photo lab on Fifth. Shut it down.' },
  ],
};
