// Case: The Earworm. Clubbers walk out of the club blank-eyed and agreeable, humming a song nobody
// can name. The trail: DJ Mesmer hides a subliminal tone under "Track Zero" and tests it on the
// floor (the staff wear custom earplugs; the violet "Lullaby" cocktail makes the crowd suggestible);
// Silas Crane of Crane Media pays for it, because he owns every radio station in the city; on
// Saturday at 3 AM the track goes out on all of them. Lenny Gold rents him the room.
// Same shape as squirt.js: keys "<room kind>:<object id>", `cat` for the 3D club's blackmail
// exchange (deal = who runs it here, supply = who pays, drop = when and where it goes out), `v3` =
// 3D club only. Super-hearing is the star: the whispers, and the tone itself.

export const EARWORM = {
  id: 'earworm', title: 'The Earworm', tagline: 'Find out what the music is doing to the crowd', theme: 'hypnosis',
  need: 8,
  rep: 25,
  clues: {
    'bar:glass': { drink: true, flavour: true, note: 'The bar pushes "Lullaby", a violet cocktail',
      text: 'A violet cocktail nobody ordered, faintly sweet. The bartender calls it a <b>Lullaby</b>: "Makes the music hit different."' },
    'bar:napkin': { cat: 'deal', note: 'Napkin: "Track Zero, 1 AM. Full room. — M"',
      text: 'A napkin with a setlist doodle on it: <b>"Track Zero, 1 AM. Full room. — M"</b>' },
    'bar:pills': { cat: 'deal', note: 'Pills marked FOCUS, for the staff only',
      text: 'A zip bag of white pills stamped <b>FOCUS</b>, and a note: "Staff only. Take before one." Somebody doesn\'t want the staff dancing.' },
    'bar:coaster': { item: 'VIP wristband', flavour: true, note: 'A VIP wristband under a coaster',
      text: 'Something stiff under the coaster: a <b>VIP wristband</b>.' },
    'bar:phone': { cat: 'drop', note: 'Text: "Saturday 3 AM. KRNC. Bring the master."',
      text: 'A phone, face down, buzzing: <b>"Saturday 3 AM. KRNC. Bring the master."</b>' },
    'bar:jar': { flavour: true, note: 'The tip jar is full of earplug wrappers',
      text: 'The tip jar is half cash, half little foam-earplug wrappers. The staff go through a lot of them.' },

    'entrance:tickets': { flavour: true, note: 'Coat tickets stamped "TEST GROUP B"',
      text: 'Claim tickets with a stamp on the back: <b>"TEST GROUP B"</b>. Last week\'s say "GROUP A".' },
    'entrance:jacket': { cat: 'supply', note: 'A Crane Media staff badge in a jacket',
      text: 'A sharp jacket. In the pocket, a lanyard: <b>Crane Media · Research Division</b>.' },
    'entrance:list': { cat: 'deal', note: 'Door list: "MESMER: Track Zero at 1. Keep the room full."',
      text: 'The door list. At the top, underlined: <b>"MESMER plays Track Zero at 1. Keep the room FULL."</b>' },
    'entrance:mints': { flavour: true, note: 'Free mints that taste of the Lullaby',
      text: 'A bowl of free mints. They taste exactly like the violet cocktail.' },
    'entrance:band': { item: 'VIP wristband', flavour: true, note: 'A spare VIP wristband',
      text: 'A spare <b>VIP wristband</b>, left on the counter.' },

    'main:phone': { cat: 'supply', note: 'Text to Mesmer: "94% compliance. Raise the gain." — S.C.',
      text: 'The DJ\'s phone: <b>"Group B: 94% compliance. Raise the gain for Saturday. — S.C."</b>' },
    'main:setlist': { cat: 'deal', note: 'Set list: "1:00 TRACK ZERO (nobody leaves)"',
      text: 'The set list. At 1 AM, in red: <b>"TRACK ZERO (nobody leaves)"</b>.' },
    'main:vial': { drink: true, flavour: true, note: 'A vial of Lullaby, neat',
      text: 'A little violet vial tucked behind the mixer: the Lullaby, neat.' },
    'main:mixer': { cat: 'deal', note: 'A tone generator wired into the mixer',
      text: 'Wired into the back of the mixer: a black box with one dial, marked <b>"SUB-TONE · 17.5 Hz"</b>. Too low to hear. Not too low to feel.' },
    'main:headphones': { flavour: true, note: 'The DJ\'s headphones filter out his own track',
      text: 'The DJ\'s headphones have a filter clipped into the cable. Mesmer never hears his own track.' },

    'vip:tray': { flavour: true, note: 'Custom earplugs on a silver tray, VIPs only',
      text: 'A silver tray of custom-moulded earplugs, each in a little velvet box. Up here, nobody listens.' },
    'vip:glass': { flavour: true, note: 'A half-finished Lullaby',
      text: 'A half-finished Lullaby. Whoever drank it walked off and forgot their shoes.' },
    'vip:card': { cat: 'supply', note: 'Card: "Silas Crane, CEO, Crane Media"',
      text: 'A heavy business card on the table: <b>Silas Crane · Crane Media</b>. Eleven radio stations listed on the back.' },
    'vip:watch': { flavour: true, note: 'A guest\'s watch, stopped at 1:00',
      text: 'An expensive watch left on the couch, stopped at exactly 1:00.' },
    'vip:matches': { cat: 'drop', note: 'KRNC matchbook: "SAT 3AM" inside',
      text: 'A matchbook from <b>KRNC Radio</b>. Written inside the cover: <b>"SAT 3AM"</b>.' },
    'vip:bucket': { flavour: true, note: 'Champagne on ice, untouched',
      text: 'Champagne on ice, untouched. Up here they keep their heads clear.' },

    'restroom:mirror': { cat: 'deal', note: 'A speaker behind the mirror, humming the tone',
      text: 'The mirror buzzes against your fingertips. Behind it: <b>a speaker</b>, humming the same low tone as the dance floor. Even in here.' },
    'restroom:pills': { cat: 'deal', note: 'Spare earplugs and FOCUS pills behind the towels',
      text: 'Behind the towel holder: a box of spare earplugs and more <b>FOCUS</b> pills. The staff\'s stash.' },
    'restroom:towels': { flavour: true, note: 'A hollow behind the towel holder',
      text: 'The towel holder\'s cover is loose. A hollow space behind it.' },
    'restroom:receipt': { cat: 'supply', note: 'Invoice: 40 speakers, billed to Crane Media',
      text: 'A crumpled invoice: forty in-wall speakers, installed overnight, billed to <b>Crane Media</b>.' },
    'restroom:soap': { flavour: true, note: 'Someone left a dazed message on the mirror',
      text: 'Someone wrote on the mirror in soap, over and over: "dance dance dance". They didn\'t finish.' },

    'office:ledger': { cat: 'supply', note: 'Ledger: monthly payments from "Crane Media: research"',
      text: 'The ledger: a payment in every month from <b>"Crane Media: research"</b>, bigger than the door and the bar together.' },
    'office:cash': { cat: 'drop', note: 'Cash envelope: "SAT · KRNC · AFTER"',
      text: 'A fat envelope of cash, marked <b>"SAT · KRNC · AFTER"</b>. Lenny gets paid once it\'s out.' },
    'office:phone': { cat: 'supply', note: 'Crane on the burner: "Saturday it goes citywide."',
      text: 'A burner phone. One contact: <b>S.C.</b> Last message: "Saturday it goes citywide. Then you\'ll never have to fill a room again."' },
    'office:key': { item: 'cellar key', flavour: true, note: 'The cellar key',
      text: 'A key on a red tag: <b>CELLAR</b>. You take it.' },
    'office:photo': { cat: 'deal', note: 'Photo: Mesmer and Lenny, "TEST NIGHT #12"',
      text: 'A framed photo on the desk: Lenny with his arm round a DJ in mirrored glasses. Signed <b>"Test night #12! — Mesmer"</b>.' },
    'office:monitor': { flavour: true, note: 'CCTV: the whole floor moving in perfect sync',
      text: 'The CCTV shows the dance floor from above. Every head on it is moving in perfect time. Not one is out of step.' },

    // the 3D club's own sources (v3)
    'talk:techs': { v3: true, cat: 'deal', note: 'Overheard: Mesmer pushes the hidden tone up during Track Zero',
      text: '"Mesmer wants the sub-tone up two more points during Track Zero." "Then we\'re all wearing plugs. I\'m not ending up like Group A."' },
    'talk:suits': { v3: true, cat: 'supply', note: 'Overheard: Crane wants it on every station by Saturday',
      text: '"Crane\'s numbers came back. He wants it on all eleven stations." "By Saturday?" "By Saturday."' },
    'talk:bouncers': { v3: true, cat: 'drop', note: 'Overheard: the master tape goes to the radio tower at three',
      text: '"Courier takes the master up the KRNC tower at three." "Saturday?" "Saturday. Then the whole city\'s on the guest list."' },
    'vip:host': { v3: true, cat: 'supply', note: 'Saint bragged: Crane owns KRNC; Saturday the city dances',
      text: 'Saint, pleased with himself: <b>"Silas owns every station worth owning. Saturday at three, the whole city hears Track Zero. And the whole city does what it\'s told."</b>' },
    'alley:bag': { v3: true, cat: 'drop', note: 'The courier\'s bag: a master tape, "KRNC SAT 03:00"',
      text: 'The courier\'s bag: a reel of master tape in a steel case, labelled <b>"KRNC · SAT · 03:00"</b>.' },
    'restroom:deal': { v3: true, cat: 'deal', note: 'The stall: custom earplugs handed out to the staff',
      text: 'The man in the last stall was fitting the bouncers with custom earplugs. "Before one o\'clock, or you\'ll be dancing too."' },
    'storage:stash': { v3: true, cat: 'deal', note: 'Behind the beer: crates of speakers and tone boxes',
      text: 'Behind the beer crates: crates of in-wall speakers and spare tone boxes, every one marked <b>"SUB-TONE"</b>.' },
    'bar:spiked': { v3: true, cat: 'deal', note: 'X-ray: the Lullaby is laced with a sedative',
      text: 'X-ray shows a sediment settling in the violet glass: a sedative. The Lullaby makes the crowd easy to steer.' },
    'uv:wall': { v3: true, cat: 'drop', note: 'UV writing: "KRNC · SAT · 3AM"',
      text: 'Under the drug-vision glow the wall is covered in UV marker: the stock code, and <b>"KRNC · SAT · 3AM"</b>.' },
    'boss:confession': { v3: true, cat: 'drop', note: 'Lenny Gold confessed: Mesmer runs it, Crane pays, Saturday 3 AM on KRNC',
      text: 'Lenny folds: Mesmer runs the tests on his floor, Silas Crane pays for the room, and on Saturday at 3 AM the track goes out on every Crane station from the KRNC tower.' },
  },
  solvedText: 'Mesmer hides the signal in Track Zero, Silas Crane pays for it, and on Saturday at 3 AM it goes out citywide from the KRNC tower.',
  drugName: 'Lullaby', uvLine: 'KRNC SAT 3AM',
  carrierLine: 'Custom earplugs: he\'s staff, and he knows not to listen.',
  talks: [
    { id: 'techs', who: 'Two sound techs', clue: 'talk:techs' },
    { id: 'suits', who: 'Two men in suits', clue: 'talk:suits' },
    { id: 'bouncers', who: 'Two bouncers', clue: 'talk:bouncers' },
  ],
  rumours: [
    { id: 'crane', text: 'Only Silas Crane\'s people get past the VIP rope tonight.', teach: 'who' },
    { id: 'zero', text: 'Wait for Track Zero. The one with no name. Everyone loses it.', teach: 'track' },
    { id: 'plugs', text: 'Every bouncer puts earplugs in at midnight. Every single one.', teach: 'plugs' },
    { id: 'hum', text: 'I can\'t stop humming it. I don\'t even know what it is.' },
    { id: 'groupa', text: 'My cousin came last week. He hasn\'t said no to anything since.' },
    { id: 'swap', text: 'Bouncers lose it at the drop. Staff door\'s wide open for a beat.' },
    { id: 'cams', text: 'Lenny\'s got a camera in every room. Even the restroom.' },
    { id: 'alley', text: 'There\'s a courier out back with a steel case. Never puts it down.' },
  ],
  // only with super-hearing on (she can hear the tone itself, under everything)
  whispers: [
    { id: 'pass', text: 'Tell Saint that Crane sent you. Works every time.', teach: 'who' },
    { id: 'tone', text: 'Under the bass: a hum, too low for anyone else. It\'s in every speaker.' },
    { id: 'code', text: 'Office code\'s {CODE}. Lenny never changes it.', code: true },
    { id: 'stash', text: 'The spare tone boxes are in the stock room, behind the beer.' },
  ],
  vip: {
    host: 'Dorian Saint',
    intro: '"Welcome to the quiet room. Up here we can hear ourselves think. Can you?"',
    questions: [
      { id: 'who', q: '"Who sent you up?"', answer: 'crane',
        options: [{ label: '"Lenny did."', value: 'lenny' }, { label: '"Silas Crane."', value: 'crane' }, { label: '"Mesmer."', value: 'mesmer' }, { label: '"Nobody. I just walked in."', value: 'none' }] },
      { id: 'track', q: '"Favourite track tonight?"', answer: 'zero',
        options: [{ label: '"Whatever\'s loudest."', value: 'loud' }, { label: '"I don\'t really listen."', value: 'none' }, { label: '"The one with no name."', value: 'zero' }, { label: '"Something old."', value: 'old' }] },
      { id: 'plugs', q: 'He taps his ear. "Plugs in?"', answer: 'midnight',
        options: [{ label: '"Plugs? In a club?"', value: 'what' }, { label: '"I like it loud."', value: 'loud' }, { label: '"Lost them."', value: 'lost' }, { label: '"Since midnight. Always."', value: 'midnight' }] },
    ],
    win: 'vip:host',
  },
  boss: {
    name: 'Lenny Gold',
    steps: [
      { cat: 'deal', line: '"A DJ plays music, hero. That\'s the whole job description."' },
      { cat: 'supply', line: '"And who would pay good money for a song nobody can even name?"' },
      { cat: 'drop', line: '"Even if you\'re right, you\'ll never stop it going out."' },
    ],
    confession: 'boss:confession',
  },
  questions: [
    { q: 'Who is hiding the signal in the music?', answer: 'mesmer',
      options: [{ label: 'The bartender', value: 'bar' }, { label: 'DJ Mesmer', value: 'mesmer' }, { label: 'Dorian Saint', value: 'saint' }, { label: 'A sound tech', value: 'tech' }] },
    { q: 'Who is paying for it?', answer: 'crane',
      options: [{ label: 'Lenny Gold', value: 'lenny' }, { label: 'Silas Crane, Crane Media', value: 'crane' }, { label: 'The city council', value: 'council' }, { label: 'A rival club', value: 'rival' }] },
    { q: 'When and where does it go out to the whole city?', answer: 'krnc',
      options: [{ label: 'Tonight, from the club', value: 'club' }, { label: 'Friday, the stadium', value: 'stadium' }, { label: 'Saturday 3 AM, the KRNC tower', value: 'krnc' }, { label: 'Sunday, city hall', value: 'hall' }] },
  ],
  leads: [
    { id: 'earworm-broadcast', name: 'The broadcast: Crane Media studio', kind: 'special', venue: 'Penthouse', theme: 'mindcontrol', reward: 120,
      by: ['bar:phone', 'office:cash', 'vip:matches', 'uv:wall', 'alley:bag'],
      blurb: 'Saturday at 3 AM Track Zero goes out on every Crane station. Get to the studio and pull the plug.' },
    { id: 'earworm-lab', name: 'Mesmer\'s sound lab', kind: 'special', venue: 'Underground Lair', theme: 'hypnosis', reward: 100,
      by: ['main:mixer', 'restroom:mirror', 'storage:stash', 'main:setlist', 'restroom:receipt'],
      blurb: 'Mesmer builds the signal in a lab under the city. Wreck it and wake his test subjects.' },
    { id: 'earworm-plant', name: 'The record pressing plant', kind: 'street', reward: 80,
      by: ['restroom:receipt', 'entrance:jacket'],
      blurb: 'Crane is pressing Track Zero onto vinyl for every club in town. Stop the shipment.' },
  ],
};
