// Case: Flashpoint Live (the Flashpoint club). Every Friday the gossip streamer Roxy Flash traps a
// celebrity on her club's hot seat and humiliates them live, the audience paying to vote on the
// dare. Tonight's star is supposed to be Supergirl. The trail: Roxy runs the show (her paparazzi
// work the floor); Dmitri Volk, "Mister Odds", runs the betting book on it; the season finale goes
// out from the Grand Arena stage on Saturday night.
// Flashpoint's own danger (press: club3d/press.js): the paparazzi never stop hunting her. Every
// second in a lens is scandal; at 100 she's dragged to the hot seat and has to struggle free while
// the screens play it to the room.
// Same shape as squirt.js: keys "<room kind>:<object id>", `cat` for the owner's confrontation
// (deal = who runs the show, supply = who bankrolls it, drop = where the finale goes out).
import { CLIPS } from '../../club3d/clips.js';

export const FLASHPOINT = {
  id: 'flashpoint', title: 'Flashpoint Live', tagline: 'Stay out of the lenses. Find who runs the show.', theme: 'extortion',
  club: 'Flashpoint', room: 'runway', difficulty: 'hard',
  press: { n: 5, rate: 16, catwalk: 2.2, range: 8, fov: 0.9 },
  clips: { wall: [...CLIPS.shame, ...CLIPS.press], trap: CLIPS.captive, shame: CLIPS.shame },
  events: ['redcarpet', 'raid', 'firealarm', 'fight'],
  need: 8,
  rep: 40,
  clues: {
    'bar:glass': { drink: true, flavour: true, note: 'The "Flashbang" shot: it fizzes white',
      text: 'A shot glass of something that fizzes white. The bartender calls it a <b>Flashbang</b>. "Makes the cameras love you."' },
    'bar:napkin': { cat: 'deal', note: 'Napkin: "Hot seat at 1. Make her cry. — R."',
      text: 'A napkin with a sketch of a chair under a spotlight: <b>"Hot seat at 1. Make her cry. — R."</b>' },
    'bar:pills': { cat: 'deal', note: 'Pills that make a guest "camera-ready" (pliant)',
      text: 'A bag of pills labelled <b>"CAMERA-READY"</b>. Pliant guests make good television.' },
    'bar:coaster': { item: 'VIP wristband', flavour: true, note: 'A VIP wristband under a coaster',
      text: 'Something stiff under the coaster: a <b>VIP wristband</b>, printed with a camera flash.' },
    'bar:phone': { cat: 'drop', note: 'Text: "Finale Saturday. Grand Arena. 20,000 seats."',
      text: 'A phone, face down, buzzing: <b>"Finale Saturday. Grand Arena. Twenty thousand seats. Bring the star."</b>' },
    'bar:jar': { flavour: true, note: 'The tip jar is full of betting slips',
      text: 'The tip jar is full of betting slips: "WILL SHE CRY? 3-1".' },

    'entrance:tickets': { flavour: true, note: 'Coat tickets marked "AUDIENCE"',
      text: 'Claim tickets stamped <b>AUDIENCE</b>, each with a seat in front of the stage.' },
    'entrance:jacket': { cat: 'supply', note: 'A betting-book ledger page in a fur coat',
      text: 'A fur coat. In the pocket, a torn page of odds: <b>"FLASHPOINT: SUPERGIRL. House: Volk."</b>' },
    'entrance:list': { cat: 'deal', note: 'Door list: "Roxy\'s crew: cameras in, no questions."',
      text: 'The door list. At the top: <b>"Roxy\'s crew: cameras in, no questions."</b>' },
    'entrance:mints': { flavour: true, note: 'Mints wrapped like film canisters',
      text: 'A bowl of mints wrapped like little film canisters.' },
    'entrance:band': { item: 'VIP wristband', flavour: true, note: 'A spare VIP wristband',
      text: 'A spare <b>VIP wristband</b>, left on the counter.' },

    'main:phone': { cat: 'deal', note: 'The DJ\'s phone: "Roxy cues the hot seat on the drop"',
      text: 'The DJ\'s phone: <b>"Roxy cues the hot seat on the second drop. Lights on the chair, cameras on her face."</b>' },
    'main:setlist': { flavour: true, note: 'Set list: "1:00 HOT SEAT (all screens)"',
      text: 'The set list. At 1 AM, in red: <b>"HOT SEAT (all screens)"</b>.' },
    'main:vial': { drink: true, flavour: true, note: 'A vial of Flashbang, neat',
      text: 'A little vial of fizzing white liquid behind the mixer: the Flashbang, neat.' },
    'main:mixer': { flavour: true, note: 'A stream encoder: "FLASHPOINT LIVE · 2.1M WATCHING"',
      text: 'Wired into the mixer: a stream encoder. The little screen reads <b>"FLASHPOINT LIVE · 2.1M WATCHING"</b>.' },
    'main:headphones': { flavour: true, note: 'Headphones with a director\'s talkback',
      text: 'The DJ\'s headphones have a talkback mic: Roxy talks straight into his ear.' },

    'vip:tray': { flavour: true, note: 'A tray of camera-ready pills, sorted by colour',
      text: 'A silver tray of pills sorted by colour. A card: "for the star".' },
    'vip:glass': { flavour: true, note: 'A half-finished Flashbang',
      text: 'A half-finished Flashbang. Its drinker is on the screens right now, crying.' },
    'vip:card': { cat: 'supply', note: 'Card: "Dmitri Volk. The House always wins."',
      text: 'A heavy black card: <b>Dmitri Volk</b>. Under the name: "The House always wins."' },
    'vip:watch': { flavour: true, note: 'A watch with a countdown: "TO AIR 00:42"',
      text: 'A watch left on the couch, counting down: <b>TO AIR 00:42</b>.' },
    'vip:matches': { cat: 'drop', note: 'Matchbook: "Grand Arena · Backstage"',
      text: 'A matchbook from the <b>Grand Arena</b>. Inside: <b>"SAT · BACKSTAGE · FINALE"</b>.' },
    'vip:bucket': { flavour: true, note: 'Champagne on ice, for the ratings',
      text: 'Champagne on ice with a tag: "Open when the ratings beat last week".' },

    'restroom:mirror': { flavour: true, note: 'A camera lens behind the mirror',
      text: 'The mirror is two-way: behind it, a <b>camera</b>, streaming.' },
    'restroom:pills': { cat: 'deal', note: 'Camera-ready pills, bagged',
      text: 'A bag of camera-ready pills behind the cistern. Bagged.' },
    'restroom:towels': { flavour: true, note: 'A hollow behind the towel holder',
      text: 'A hollow behind the towel holder: spare batteries, spare memory cards.' },
    'restroom:receipt': { cat: 'supply', note: 'Receipt: the stream\'s servers, paid by "the House"',
      text: 'A crumpled receipt: the stream\'s servers, a year in advance, paid by <b>"the House"</b>.' },
    'restroom:soap': { flavour: true, note: 'Someone wrote "SMILE FOR THE CAMERA"',
      text: 'Someone wrote on the mirror in soap: <b>"SMILE, YOU\'RE ON FLASHPOINT."</b>' },

    'office:ledger': { cat: 'supply', note: 'Ledger: the House takes every bet on every episode',
      text: 'The ledger: every episode, every celebrity, every bet. The <b>House</b> took them all.' },
    'office:cash': { cat: 'drop', note: 'Envelope: "ARENA DEPOSIT · SATURDAY"',
      text: 'An envelope of cash marked <b>"GRAND ARENA · DEPOSIT · SAT"</b>.' },
    'office:phone': { cat: 'supply', note: 'Volk on the burner: "If she escapes, you pay the book."',
      text: 'A burner phone. One contact: <b>Mr Odds</b>. Last message: "If she escapes, you pay the book. All of it."' },
    'office:key': { item: 'cellar key', flavour: true, note: 'The control-room key',
      text: 'A key on a red tag: <b>CONTROL</b>. You take it.' },
    'office:photo': { cat: 'deal', note: 'Photo: Roxy Flash at a gossip award',
      text: 'A framed photo: <b>Roxy Flash</b> holding a gossip award. "Queen of the Hot Seat."' },
    'office:monitor': { flavour: true, note: 'Monitors: every camera on the floor, all on you',
      text: 'The monitors show every camera on the floor. Most of them are pointed at where you were standing a minute ago.' },

    'talk:crew': { v3: true, cat: 'deal', note: 'Overheard: Roxy runs the hot seat and her crew',
      text: '"Roxy wants her in the chair by one." "Supergirl? Live?" "Biggest episode we\'ve ever done."' },
    'talk:bookies': { v3: true, cat: 'supply', note: 'Overheard: Volk takes the bets, the House pays for it all',
      text: '"Volk\'s book on tonight is the biggest ever." "And if she gets out?" "Then the House loses. The House doesn\'t lose."' },
    'talk:bouncers': { v3: true, cat: 'drop', note: 'Overheard: the finale is at the Grand Arena on Saturday',
      text: '"Saturday\'s the finale." "Here?" "No. The Grand Arena. Twenty thousand seats and the whole city watching."' },
    'vip:host': { v3: true, cat: 'deal', note: 'Jett bragged: Roxy Flash puts every star in the hot seat',
      text: 'Jett, pleased with himself: <b>"Roxy picks the star, Roxy writes the dare, Roxy rolls the cameras. Tonight it\'s you, sweetheart."</b>' },
    'alley:bag': { v3: true, cat: 'drop', note: 'The courier\'s bag: arena passes, "SAT FINALE"',
      text: 'The courier\'s bag: a stack of Grand Arena backstage passes, <b>"FLASHPOINT FINALE · SAT"</b>.' },
    'restroom:deal': { v3: true, cat: 'deal', note: 'The stall: a paparazzo selling footage to Roxy\'s crew',
      text: 'The man in the last stall was copying memory cards. "Roxy buys anything with you in it. Anything."' },
    'storage:stash': { v3: true, cat: 'drop', note: 'Behind the crates: the arena stage set, crated',
      text: 'Behind the crates: the hot seat\'s twin, crated up and stencilled <b>"GRAND ARENA · SAT"</b>.' },
    'bar:spiked': { v3: true, cat: 'deal', note: 'X-ray: the Flashbang is laced with a sedative',
      text: 'X-ray shows the fizz is hiding a sedative: the Flashbang is how they get the stars into the chair.' },
    'uv:wall': { v3: true, cat: 'drop', note: 'UV writing: "ARENA SAT"',
      text: 'Under the glow the wall is covered in UV marker: the stock code, and <b>"ARENA SAT"</b>.' },
    'boss:confession': { v3: true, cat: 'drop', note: 'Roxy Flash confessed: her show, Volk\'s money, the Grand Arena on Saturday',
      text: 'Roxy folds: she runs the show, Dmitri Volk\'s House bankrolls it and takes the bets, and Saturday\'s finale goes out live from the Grand Arena.' },
  },
  solvedText: 'Roxy Flash runs the show, Dmitri Volk\'s House bankrolls it and books the bets, and the finale goes out from the Grand Arena on Saturday.',
  drugName: 'The Flashbang', uvLine: 'ARENA SAT',
  carrierLine: 'A memory card in his pocket: he shoots for Roxy.',
  talks: [
    { id: 'crew', who: 'Two camera operators', clue: 'talk:crew' },
    { id: 'bookies', who: 'Two bookies', clue: 'talk:bookies' },
    { id: 'bouncers', who: 'Two bouncers', clue: 'talk:bouncers' },
  ],
  rumours: [
    { id: 'roxy', text: 'Only Roxy\'s people get past the VIP rope.', teach: 'who' },
    { id: 'chair', text: 'Whoever ends up in that chair, the whole city sees it.', teach: 'chair' },
    { id: 'smile', text: 'The trick is to smile. They hate it when you smile.', teach: 'smile' },
    { id: 'odds', text: 'Three to one she cries. I put fifty on it.' },
    { id: 'lens', text: 'Stay off the catwalk. Every lens in here is on it.' },
    { id: 'drop', text: 'At the drop the flashes all go off at once. Nobody sees a thing.' },
    { id: 'cams', text: 'There\'s a camera in the restroom mirror. Don\'t ask.' },
    { id: 'alley', text: 'There\'s a courier out back with a bag of arena passes.' },
  ],
  whispers: [
    { id: 'pass', text: 'Tell Jett that Roxy sent you. He\'ll believe anything.', teach: 'who' },
    { id: 'book', text: 'Volk\'s men are taking bets in the lounge.' },
    { id: 'code', text: 'Office code\'s {CODE}. Roxy never changes it.', code: true },
    { id: 'stash', text: 'The arena set\'s in the stock room, behind the crates.' },
  ],
  vip: {
    host: 'Jett',
    intro: '"Welcome to the green room. Everybody up here is about to be famous. Or infamous."',
    questions: [
      { id: 'who', q: '"Who sent you up?"', answer: 'roxy',
        options: [{ label: '"Dmitri Volk."', value: 'volk' }, { label: '"Nobody."', value: 'none' }, { label: '"Roxy did."', value: 'roxy' }, { label: '"The DJ."', value: 'dj' }] },
      { id: 'chair', q: '"Ever been in the chair?"', answer: 'city',
        options: [{ label: '"What chair?"', value: 'what' }, { label: '"And let the whole city see?"', value: 'city' }, { label: '"Every week."', value: 'week' }, { label: '"Once."', value: 'once' }] },
      { id: 'smile', q: 'He raises a camera. "Give me something."', answer: 'smile',
        options: [{ label: 'Cover your face', value: 'cover' }, { label: 'Smile', value: 'smile' }, { label: 'Walk away', value: 'away' }, { label: 'Grab the camera', value: 'grab' }] },
    ],
    win: 'vip:host',
  },
  boss: {
    name: 'Roxy Flash',
    steps: [
      { cat: 'deal', line: '"I make entertainment, hero. People love it. You\'ll love it too."' },
      { cat: 'supply', line: '"And who\'d pay for all this? Ad money, darling."' },
      { cat: 'drop', line: '"Even if you\'re right, Saturday\'s finale is sold out."' },
    ],
    confession: 'boss:confession',
  },
  questions: [
    { q: 'Who runs the hot seat?', answer: 'roxy',
      options: [{ label: 'The DJ', value: 'dj' }, { label: 'Roxy Flash', value: 'roxy' }, { label: 'Jett', value: 'jett' }, { label: 'A paparazzo', value: 'pap' }] },
    { q: 'Who bankrolls it and takes the bets?', answer: 'volk',
      options: [{ label: 'An ad agency', value: 'ads' }, { label: 'The Daily Scoop', value: 'scoop' }, { label: 'Dmitri Volk, the House', value: 'volk' }, { label: 'The city council', value: 'council' }] },
    { q: 'Where does the finale go out?', answer: 'arena',
      options: [{ label: 'Here, next Friday', value: 'here' }, { label: 'The TV studio, Sunday', value: 'tv' }, { label: 'The Grand Arena, Saturday', value: 'arena' }, { label: 'Online only', value: 'online' }] },
  ],
  leads: [
    { id: 'flash-arena', name: 'The finale: the Grand Arena', kind: 'special', venue: 'Penthouse', theme: 'extortion', reward: 120,
      by: ['bar:phone', 'office:cash', 'vip:matches', 'uv:wall', 'alley:bag', 'storage:stash'],
      blurb: 'Saturday\'s finale goes out live from the Grand Arena. Pull the plug before the star takes the chair.' },
    { id: 'flash-house', name: 'The House: Volk\'s betting floor', kind: 'special', venue: 'High-Roller Suite', theme: 'gang', reward: 100,
      by: ['entrance:jacket', 'vip:card', 'office:ledger', 'office:phone', 'restroom:receipt'],
      blurb: 'Dmitri Volk takes every bet on every episode. Shut the House down.' },
    { id: 'flash-crew', name: 'Roxy\'s paparazzi den', kind: 'street', reward: 80,
      by: ['restroom:deal', 'main:phone'],
      blurb: 'Roxy\'s crew stores every frame they shoot in a studio downtown. Wipe it.' },
  ],
};
