// Case: Halo (The Hive). A gold powder called Halo is all over the city's clubs: a party high for a
// human, a second sight for a Kryptonian. The trail: Bianca Rook, "Queen Bee", owns the Hive and
// runs her dealers (the "drones") on its floor; Dr Amos Kell cooks it at Helix Labs from stolen
// kryptonite research; it ships out in honey jars from Pier 9, Thursday at dawn.
// The rule of this club (highOnly): the Hive only opens up to someone who's on it. Sober, the
// drones clam up, the search spots show nothing and the doors stay shut: she solves it high, and
// keeps herself in the band between "high enough" and "passed out".
// Same shape as squirt.js: keys "<room kind>:<object id>", `cat` for the owner's confrontation
// (deal = who pushes it, supply = who cooks it, drop = where it ships), `v3` = 3D club only.
import { CLIPS } from '../../club3d/clips.js';

export const HALO = {
  id: 'halo', title: 'Halo', tagline: 'Solve it high: the Hive only talks to its own', theme: 'drugs',
  club: 'The Hive', room: 'hive', difficulty: 'hard',
  highOnly: { min: 30, line: 'Sober, the Hive is just a club. Nobody here talks to a narc in a cape.' },
  clips: { wall: CLIPS.high, trap: CLIPS.captive, shame: CLIPS.high },
  events: ['raid', 'firealarm', 'fight'],
  need: 8,
  rep: 40,
  clues: {
    'bar:glass': { drink: true, flavour: true, note: 'The "Honey Shot" glitters gold',
      text: 'A short glass of something amber with gold glitter swirling in it. The bartender calls it a <b>Honey Shot</b>. "First one\'s on the Queen."' },
    'bar:napkin': { cat: 'deal', note: 'Napkin: "Drones work the pockets. Queen takes 60."',
      text: 'A napkin with a doodled honeycomb, each cell numbered. Underneath: <b>"Drones work the pockets. Queen takes 60."</b>' },
    'bar:pills': { cat: 'deal', note: 'Gold capsules stamped with a bee',
      text: 'A bag of gold capsules, each stamped with a tiny <b>bee</b>. The drones hand these out by the dozen.' },
    'bar:coaster': { item: 'VIP wristband', flavour: true, note: 'A VIP wristband under a coaster',
      text: 'Something stiff under the coaster: a <b>VIP wristband</b>, gold, hexagon-shaped.' },
    'bar:phone': { cat: 'drop', note: 'Text: "Pier 9, Thursday, first light. Honey jars."',
      text: 'A phone, face down, buzzing: <b>"Pier 9. Thursday, first light. 400 jars of honey."</b>' },
    'bar:jar': { flavour: true, note: 'The tip jar is full of gold glitter',
      text: 'The tip jar is half cash, half gold glitter. Everyone in here sheds it.' },

    'entrance:tickets': { flavour: true, note: 'Coat tickets punched with a bee: "regulars"',
      text: 'Claim tickets, half of them punched with a little bee. The bouncer waves those straight through.' },
    'entrance:jacket': { cat: 'supply', note: 'A Helix Labs pass in a lab coat',
      text: 'A lab coat on a club coat hook. Clipped to it: <b>Helix Labs · Dr A. Kell · Level 4</b>.' },
    'entrance:list': { cat: 'deal', note: 'Door list: "Drones in free. Narcs: call the Queen."',
      text: 'The door list. At the top, underlined twice: <b>"Drones in free. Narcs: call the Queen."</b>' },
    'entrance:mints': { flavour: true, note: 'Free "mints" that taste of honey',
      text: 'A bowl of free mints. They taste of honey, and leave your tongue tingling.' },
    'entrance:band': { item: 'VIP wristband', flavour: true, note: 'A spare VIP wristband',
      text: 'A spare <b>VIP wristband</b>, hexagonal and gold, left on the counter.' },

    'main:phone': { cat: 'deal', note: 'The DJ\'s phone: "Queen says double the drones tonight"',
      text: 'The DJ\'s phone, unlocked: <b>"Queen says double the drones tonight. Supergirl\'s been sniffing round."</b>' },
    'main:setlist': { cat: 'deal', note: 'Set list: drops marked "SWARM"',
      text: 'The set list. Every drop is marked <b>SWARM</b>: when the lights go out, the drones go to work.' },
    'main:vial': { drink: true, flavour: true, note: 'A vial of Halo, neat',
      text: 'A little vial of gold dust tucked behind the mixer: Halo, uncut. It\'s warm to the touch.' },
    'main:mixer': { flavour: true, note: 'A bee sticker on every fader',
      text: 'A bee sticker on every fader of the mixer. The Queen marks what\'s hers.' },
    'main:headphones': { flavour: true, note: 'Headphones with "B.R." scratched in',
      text: 'The DJ\'s headphones, "B.R." scratched into the band. They belong to the boss.' },

    'vip:tray': { cat: 'deal', note: 'A silver tray of Halo, cut into lines',
      text: 'A silver tray on the low table, gold powder cut into neat lines. The Queen\'s private stock.' },
    'vip:glass': { flavour: true, note: 'A half-finished Honey Shot',
      text: 'A half-finished Honey Shot, lipstick on the rim. Gold glitter on the couch.' },
    'vip:card': { cat: 'supply', note: 'Card: "Helix Labs. Dr Amos Kell, Director of Research"',
      text: 'A business card on the table: <b>Helix Labs · Dr Amos Kell · Director of Research</b>. On the back, a formula, and the word <b>"KRYPTON"</b> underlined.' },
    'vip:watch': { flavour: true, note: 'A Rolex with honey on the strap',
      text: 'An expensive watch left on the couch, sticky with honey.' },
    'vip:matches': { cat: 'drop', note: 'Matchbook: "Pier 9 Apiary Supply"',
      text: 'A matchbook: <b>"Pier 9 Apiary Supply · Wholesale Honey"</b>. Inside: "THU 5AM".' },
    'vip:bucket': { flavour: true, note: 'Champagne on ice, gold flakes floating in it',
      text: 'Champagne on ice. Somebody has stirred gold flakes into it.' },

    'restroom:mirror': { flavour: true, note: 'The mirror: "THE QUEEN SEES YOU" in gold',
      text: 'Written across the mirror in gold lipstick: <b>"THE QUEEN SEES YOU."</b>' },
    'restroom:pills': { cat: 'deal', note: 'A bag of Halo, bagged as evidence',
      text: 'Gold powder in a dealer\'s baggie, a bee printed on it. Bagged.' },
    'restroom:towels': { flavour: true, note: 'A hollow behind the towel holder',
      text: 'The towel holder\'s cover is loose. A hollow space behind it, dusted gold.' },
    'restroom:receipt': { cat: 'supply', note: 'Invoice: lab glassware, billed to Helix Labs',
      text: 'A crumpled invoice: reaction flasks and a pill press, billed to <b>Helix Labs</b>, delivered to the Hive.' },
    'restroom:soap': { flavour: true, note: 'Someone wrote "I CAN SEE THROUGH WALLS" in soap',
      text: 'Someone wrote on the mirror in soap: "I CAN SEE THROUGH WALLS". They couldn\'t.' },

    'office:ledger': { cat: 'deal', note: 'Ledger: every drone, every pocket, the Queen\'s cut',
      text: 'The ledger: a page per drone, a column per dance pocket, and the Queen\'s sixty per cent in red.' },
    'office:cash': { cat: 'drop', note: 'Cash envelope: "PIER 9 · DOCK FEE · THURSDAY"',
      text: 'A fat envelope of cash, marked <b>"PIER 9 · DOCK FEE · THU"</b>.' },
    'office:phone': { cat: 'supply', note: 'Kell on the burner: "The Kryptonian batch is ready."',
      text: 'A burner phone. One contact: <b>Dr K.</b> Last message: "The Kryptonian batch is ready. One hit and she\'ll see the whole city. Two and she\'ll never want to stop."' },
    'office:key': { item: 'cellar key', flavour: true, note: 'The cellar key',
      text: 'A key on a gold tag: <b>CELLAR</b>. You take it.' },
    'office:photo': { cat: 'supply', note: 'Photo: the Queen and Dr Kell at Helix Labs',
      text: 'A framed photo: Bianca Rook in a hard hat beside a man in a lab coat, under a <b>Helix Labs</b> sign. "Partners!"' },
    'office:monitor': { flavour: true, note: 'CCTV: the drones moving through the pockets',
      text: 'The CCTV shows the dance pockets from above. Gold-glittered drones move between them like bees between flowers.' },

    // the 3D club's own sources (v3)
    'talk:drones': { v3: true, cat: 'deal', note: 'Overheard: the drones work the pockets for the Queen',
      text: '"Pocket three\'s dry." "Then work pocket four. The Queen wants every pocket glowing by the drop."' },
    'talk:chemists': { v3: true, cat: 'supply', note: 'Overheard: Kell cooks it at Helix, from kryptonite research',
      text: '"Kell says the new batch is cut with the Helix stuff. The green rock research." "On a human it\'s a party." "On her?"' },
    'talk:bouncers': { v3: true, cat: 'drop', note: 'Overheard: the honey van leaves Pier 9 at dawn Thursday',
      text: '"Honey van loads at Pier 9." "When?" "Thursday, first light. Four hundred jars. Not one of them honey."' },
    'vip:host': { v3: true, cat: 'deal', note: 'Saffron bragged: the Queen runs every drone on the floor',
      text: 'Saffron, gold-dusted and pleased with herself: <b>"Every drone on that floor answers to the Queen. Bianca Rook. She\'s the only one who decides who glows."</b>' },
    'alley:bag': { v3: true, cat: 'drop', note: 'The courier\'s bag: honey jars, "PIER 9 THU"',
      text: 'The courier\'s bag: six honey jars, gold powder under a thin layer of honey. The labels: <b>"PIER 9 · THU"</b>.' },
    'restroom:deal': { v3: true, cat: 'deal', note: 'The stall: a drone restocking from the Queen\'s bag',
      text: 'The man in the last stall was refilling his pockets from a bag with a gold bee on it. "Queen\'s orders: double tonight."' },
    'storage:stash': { v3: true, cat: 'supply', note: 'Behind the beer: a pill press, stamped HELIX',
      text: 'Behind the beer crates: a pill press and drums of gold powder, every drum stencilled <b>HELIX LABS</b>.' },
    'bar:spiked': { v3: true, cat: 'deal', note: 'X-ray: the Honey Shot is laced with Halo',
      text: 'X-ray shows the gold in the glass isn\'t glitter: it\'s Halo, a full dose in every Honey Shot.' },
    'uv:wall': { v3: true, cat: 'drop', note: 'Halo-sight: "PIER 9 · THU · DAWN" on the wall',
      text: 'Through the Halo glow the wall is covered in writing nobody sober can see: the stock code, and <b>"PIER 9 · THU · DAWN"</b>.' },
    'boss:confession': { v3: true, cat: 'drop', note: 'Bianca Rook confessed: her drones, Kell\'s batch, Pier 9 on Thursday',
      text: 'The Queen folds: her drones push it, Dr Kell cooks it at Helix Labs, and on Thursday at dawn the honey van takes four hundred jars out of Pier 9.' },
  },
  solvedText: 'The Queen\'s drones push it, Dr Kell cooks it at Helix Labs, and the honey van ships it out of Pier 9 on Thursday at dawn.',
  drugName: 'Halo', uvLine: 'PIER 9 THU DAWN',
  carrierLine: 'Gold dust on his sleeves: he\'s a drone.',
  talks: [
    { id: 'drones', who: 'Two drones', clue: 'talk:drones' },
    { id: 'chemists', who: 'Two lab coats', clue: 'talk:chemists' },
    { id: 'bouncers', who: 'Two bouncers', clue: 'talk:bouncers' },
  ],
  rumours: [
    { id: 'queen', text: 'The Queen only lets glowing people up to the VIP.', teach: 'who' },
    { id: 'swarm', text: 'When the lights go out it\'s a swarm. Drones everywhere.', teach: 'swarm' },
    { id: 'pocket', text: 'Pocket four. That\'s where you score.', teach: 'pocket' },
    { id: 'see', text: 'On Halo I swear I could see the bass.' },
    { id: 'super', text: 'They say it does something else to her. To Supergirl.' },
    { id: 'drop', text: 'At the drop the bouncers are blind. Staff door\'s wide open.' },
    { id: 'cams', text: 'The Queen\'s got a camera in every pocket.' },
    { id: 'alley', text: 'There\'s a courier out back with a bag full of honey.' },
  ],
  whispers: [
    { id: 'pass', text: 'Tell Saffron the Queen sent you. She\'ll pour you one.', teach: 'who' },
    { id: 'glow', text: 'Under the music: a hum of gold. You can hear the Halo in their blood.' },
    { id: 'code', text: 'Office code\'s {CODE}. The Queen never changes it.', code: true },
    { id: 'stash', text: 'The press is in the stock room, behind the beer.' },
  ],
  vip: {
    host: 'Saffron',
    intro: '"Welcome to the honeycomb, sweetheart. You\'re glowing. Or you\'re not, and you should leave."',
    questions: [
      { id: 'who', q: '"Who let you up?"', answer: 'queen',
        options: [{ label: '"Dr Kell."', value: 'kell' }, { label: '"The Queen did."', value: 'queen' }, { label: '"The DJ."', value: 'dj' }, { label: '"I flew."', value: 'flew' }] },
      { id: 'swarm', q: '"What happens when the lights go out?"', answer: 'swarm',
        options: [{ label: '"Everybody dances."', value: 'dance' }, { label: '"The swarm."', value: 'swarm' }, { label: '"The cops come."', value: 'cops' }, { label: '"Nothing."', value: 'none' }] },
      { id: 'pocket', q: '"Where do you score?"', answer: 'four',
        options: [{ label: '"At the bar."', value: 'bar' }, { label: '"I don\'t."', value: 'none' }, { label: '"Pocket four."', value: 'four' }, { label: '"Up here."', value: 'here' }] },
    ],
    win: 'vip:host',
  },
  boss: {
    name: 'Bianca Rook',
    steps: [
      { cat: 'deal', line: '"I run a club, darling. What people bring in their pockets is their business."' },
      { cat: 'supply', line: '"And where would little me get anything that strong?"' },
      { cat: 'drop', line: '"Even if you\'re right, by Thursday it\'s in every club in the country."' },
    ],
    confession: 'boss:confession',
  },
  questions: [
    { q: 'Who runs the dealers on the Hive\'s floor?', answer: 'queen',
      options: [{ label: 'The bartender', value: 'bar' }, { label: 'Saffron', value: 'saffron' }, { label: 'Bianca Rook, the Queen', value: 'queen' }, { label: 'The DJ', value: 'dj' }] },
    { q: 'Who cooks Halo?', answer: 'kell',
      options: [{ label: 'Dr Amos Kell, Helix Labs', value: 'kell' }, { label: 'A street chemist', value: 'street' }, { label: 'The Queen herself', value: 'queen' }, { label: 'A rival club', value: 'rival' }] },
    { q: 'Where does the shipment go out?', answer: 'pier',
      options: [{ label: 'The airport, Friday', value: 'air' }, { label: 'The club\'s cellar, tonight', value: 'cellar' }, { label: 'Pier 9, Thursday at dawn', value: 'pier' }, { label: 'Helix Labs, Sunday', value: 'helix' }] },
  ],
  leads: [
    { id: 'halo-pier', name: 'The honey van: Pier 9', kind: 'special', venue: 'Warehouse', theme: 'drugs', reward: 120,
      by: ['bar:phone', 'office:cash', 'vip:matches', 'uv:wall', 'alley:bag'],
      blurb: 'Four hundred jars of Halo leave Pier 9 on Thursday at dawn. Get there first.' },
    { id: 'halo-lab', name: 'Helix Labs', kind: 'special', venue: 'Underground Lair', theme: 'drugs', reward: 100,
      by: ['entrance:jacket', 'vip:card', 'office:phone', 'storage:stash', 'restroom:receipt'],
      blurb: 'Dr Kell cooks Halo from stolen kryptonite research. Shut his lab down.' },
    { id: 'halo-drones', name: 'The drones\' stash house', kind: 'street', reward: 80,
      by: ['bar:napkin', 'office:ledger'],
      blurb: 'The Queen\'s drones restock from a house across town. Clear it out.' },
  ],
};
