// Case: Super Squirt. A new drug is being pushed through the club. The trail: Moe (the DJ) deals it
// at 2 AM, supplied by "K" (Kraken Shipping), with the next drop at Pier 9 on Thursday. Solving it
// marks the distribution points on the city map (`leads`): each a mission worth far more rep.
// Keys are "<room kind>:<object id>" (objects in scenes.js). `note` is the case-board line;
// `flavour` clues don't count toward the deduction; `drink` offers the drug; `item` hands one over.

export const SQUIRT = {
  id: 'squirt', title: 'Super Squirt', tagline: 'Find out who is pushing Super Squirt', theme: 'drugs',
  need: 8,         // clues before an accusation can be made
  rep: 25,         // solving it in the club (the leads on the map pay the big rep)
  clues: {
    'bar:glass': { drink: true, flavour: true, note: 'The bar serves glowing "house specials"',
      text: 'A glowing green drink nobody ordered. It fizzes when you lean in. The bartender calls it the house special: <b>Super Squirt</b>.' },
    'bar:napkin': { note: 'Napkin: "2 AM. Back room. Ask for Moe."',
      text: 'A napkin covered in scrawl. Under the smudges: <b>"2 AM. Back room. Ask for Moe."</b>' },
    'bar:pills': { note: 'Rainbow pills, the same glitter as the shots',
      text: 'Rainbow-speckled pills in a zip bag: the same glitter as the Super Squirt shots. Someone is cutting it here.' },
    'bar:coaster': { item: 'VIP wristband', flavour: true, note: 'A VIP wristband under a coaster',
      text: 'Something stiff under the coaster: a <b>VIP wristband</b>, left for whoever knows where to look.' },
    'bar:phone': { note: 'Text from K: "Shipment lands Thursday. Usual drop."',
      text: 'A face-down phone, still buzzing. Lock screen: <b>"Shipment lands Thursday. Usual drop. — K"</b>' },
    'bar:jar': { flavour: true, note: 'A tip jar full of hush money',
      text: 'The tip jar is stuffed with fifties. Far too much for a bar this quiet. Somebody is paying for silence.' },

    'entrance:tickets': { flavour: true, note: 'Claim ticket #13, never collected',
      text: 'Claim tickets. One number is circled in green ink: <b>#13</b>. Nobody has collected it.' },
    'entrance:jacket': { note: 'Jacket #13: cash and a card, "K — Pier 9"',
      text: 'Ticket #13\'s leather jacket. Something heavy in the pocket: a roll of cash and a card that says only <b>"K — Pier 9"</b>.' },
    'entrance:list': { note: 'Guest list: "Moe — all night, all rooms"',
      text: 'The guest list. Half the names are crossed out. One is underlined twice: <b>"Moe — all night, all rooms."</b>' },
    'entrance:mints': { note: 'Super Squirt pressed to look like mints',
      text: 'A bowl of mints. A few are green and glitter under the light: Super Squirt, pressed to look like candy.' },
    'entrance:band': { item: 'VIP wristband', flavour: true, note: 'A spare VIP wristband',
      text: 'A spare <b>VIP wristband</b>, left on the counter. Nobody will miss it.' },

    'main:phone': { note: 'DJ\'s phone: a map pin on Pier 9',
      text: 'The DJ\'s phone, propped on the mixer: a map pin on the docks. <b>Pier 9.</b>' },
    'main:setlist': { note: 'Set list: "Shadow Walk" at 2 AM, when the back room opens',
      text: 'The set list. One track circled in red: <b>"Shadow Walk"</b>. The DJ plays it every night at 2 AM, right before the back room opens.' },
    'main:vial': { drink: true, flavour: true, note: 'A vial of pure Super Squirt in the booth',
      text: 'A tiny glowing green vial tucked behind the mixer. Pure <b>Super Squirt</b>, uncut.' },
    'main:mixer': { note: 'Green residue on the DJ\'s mixer',
      text: 'The mixer\'s faders are sticky with green residue. Whoever runs this booth handles the product.' },
    'main:headphones': { note: 'The DJ\'s headphones say "MOE"',
      text: 'Headphones with a name scratched into the band: <b>"MOE"</b>.' },

    'vip:tray': { note: 'Green powder on the VIP tray',
      text: 'A silver tray dusted with glittering green powder. Super Squirt before it\'s mixed into the shots.' },
    'vip:glass': { flavour: true, note: 'A lipstick glass, left in a hurry',
      text: 'A glass with a lipstick print. Someone left in a hurry when the doors opened.' },
    'vip:card': { note: 'Kraken Shipping, Pier 9: "K" again',
      text: 'A business card with a tall ship: <b>Kraken Shipping, Pier 9</b>. "K" again.' },
    'vip:watch': { note: 'Watch stopped at 2:00: "To Moe, from K."',
      text: 'An expensive watch, stopped at 2:00. Engraved on the back: <b>"To Moe, from K."</b>' },
    'vip:matches': { note: 'Bayside Motel matchbook, room 9',
      text: 'A matchbook from the <b>Bayside Motel</b>. Room 9 is written inside the cover.' },
    'vip:bucket': { flavour: true, note: 'The VIP table runs on drug money',
      text: 'The champagne is real. The money behind it isn\'t. This table runs on Super Squirt.' },

    'restroom:mirror': { flavour: true, note: 'A lipstick number on the mirror',
      text: 'A number in lipstick on the cracked mirror, half wiped off. A phone number, or a pier.' },
    'restroom:pills': { note: 'The restroom drop point, behind the towels',
      text: 'A zip bag of glowing green pills stuck behind the towel holder. This is the drop point.' },
    'restroom:towels': { flavour: true, note: 'A hollow behind the towel holder',
      text: 'The towel holder\'s cover is loose. A hollow space behind it, just the size of a bag.' },
    'restroom:receipt': { note: 'Receipt: 40 "house specials" at 1:58 AM',
      text: 'A crumpled receipt: forty shots of the "house special", paid in cash, 1:58 AM.' },
    'restroom:soap': { flavour: true, note: 'Green powder washed off at the sink',
      text: 'The soap smells faintly of something sweet and chemical. Someone washed their hands of green powder here.' },

    'office:ledger': { note: 'Ledger: an "SS" column, ten times the bar takings',
      text: 'The ledger: two sets of numbers. Drinks on the left, and on the right a column headed <b>"SS"</b>, ten times bigger.' },
    'office:cash': { note: 'Cash banded "K — Thursday"',
      text: 'A brick of cash with a band marked <b>"K — Thursday"</b>.' },
    'office:phone': { note: 'Burner: "Usual drop. Don\'t be late again, Moe."',
      text: 'A burner phone. One contact: <b>K</b>. Last message: "Usual drop. Don\'t be late again, Moe."' },
    'office:key': { item: 'cellar key', flavour: true, note: 'The cellar key',
      text: 'A key on a red tag: <b>CELLAR</b>. You take it.' },
    'office:photo': { note: 'A photo of Pier 9 at night',
      text: 'A framed photo of the pier at night. Pier 9.' },
    'office:monitor': { flavour: true, note: 'The 2 AM security footage was erased',
      text: 'The security feed shows the back hallway. The 2 AM recording has been erased.' },
  },
  questions: [
    { q: 'Who is pushing Super Squirt inside the club?', answer: 'moe',
      options: [{ label: 'The bartender', value: 'bar' }, { label: 'Moe, the DJ', value: 'moe' }, { label: 'The coat-check girl', value: 'coat' }, { label: 'The bouncer', value: 'door' }] },
    { q: 'Who supplies him?', answer: 'k',
      options: [{ label: 'The club\'s owner', value: 'owner' }, { label: 'A street gang', value: 'gang' }, { label: '"K", of Kraken Shipping', value: 'k' }, { label: 'The Bayside Motel manager', value: 'motel' }] },
    { q: 'When and where is the next drop?', answer: 'pier',
      options: [{ label: 'Tonight, in the cellar', value: 'cellar' }, { label: '2 AM, the restroom', value: 'rest' }, { label: 'Friday, the Bayside Motel', value: 'fri' }, { label: 'Thursday, Pier 9', value: 'pier' }] },
  ],
  // distribution points unlocked on the map by a solved case: each one whose clues were found
  leads: [
    { id: 'squirt-pier9', name: 'Super Squirt drop: Pier 9', kind: 'special', venue: 'Warehouse', theme: 'drugs', reward: 120,
      by: ['entrance:jacket', 'main:phone', 'vip:card', 'office:photo'],
      blurb: 'Thursday\'s Super Squirt shipment comes in at Pier 9. Shut it down.' },
    { id: 'squirt-kraken', name: 'Kraken Shipping warehouse', kind: 'special', venue: 'Warehouse', theme: 'drugs', reward: 100,
      by: ['bar:phone', 'vip:watch', 'office:cash', 'office:phone'],
      blurb: '"K" runs Super Squirt out of the Kraken Shipping warehouse. Raid it.' },
    { id: 'squirt-motel', name: 'Bayside Motel, room 9', kind: 'street', reward: 80,
      by: ['vip:matches'],
      blurb: 'Moe\'s crew cuts the drug in room 9 of the Bayside Motel. Bust it.' },
  ],
};
