// Case: Super Squirt. A new drug is being pushed through the club. The trail: Moe (the DJ) deals it
// at 2 AM, supplied by "K" (Kraken Shipping), with the next drop at Pier 9 on Thursday. Solving it
// marks the distribution points on the city map (`leads`): each a mission worth far more rep.
// Keys are "<room kind>:<object id>" (objects in scenes.js). `note` is the case-board line;
// `flavour` clues don't count toward the deduction; `drink` offers the drug; `item` hands one over;
// `cat` (deal / supply / drop) is what a clue proves in the 3D club's blackmail exchange; `v3`
// clues only exist in the 3D club (Talkers, the VIP host, fights, the stash, drug-vision).

export const SQUIRT = {
  id: 'squirt', title: 'Super Squirt', tagline: 'Find out who is pushing Super Squirt', theme: 'drugs',
  need: 8,         // clues before an accusation can be made
  rep: 25,         // solving it in the club (the leads on the map pay the big rep)
  clues: {
    'bar:glass': { drink: true, flavour: true, note: 'The bar serves glowing "house specials"',
      text: 'A glowing green drink nobody ordered. It fizzes when you lean in. The bartender calls it the house special: <b>Super Squirt</b>.' },
    'bar:napkin': { cat: 'deal', note: 'Napkin: "2 AM. Back room. Ask for Moe."',
      text: 'A napkin covered in scrawl. Under the smudges: <b>"2 AM. Back room. Ask for Moe."</b>' },
    'bar:pills': { cat: 'deal', note: 'Rainbow pills, the same glitter as the shots',
      text: 'Rainbow-speckled pills in a zip bag: the same glitter as the Super Squirt shots. Someone is cutting it here.' },
    'bar:coaster': { item: 'VIP wristband', flavour: true, note: 'A VIP wristband under a coaster',
      text: 'Something stiff under the coaster: a <b>VIP wristband</b>, left for whoever knows where to look.' },
    'bar:phone': { cat: 'drop', note: 'Text from K: "Shipment lands Thursday. Usual drop."',
      text: 'A face-down phone, still buzzing. Lock screen: <b>"Shipment lands Thursday. Usual drop. — K"</b>' },
    'bar:jar': { flavour: true, note: 'A tip jar full of hush money',
      text: 'The tip jar is stuffed with fifties. Far too much for a bar this quiet. Somebody is paying for silence.' },

    'entrance:tickets': { flavour: true, note: 'Claim ticket #13, never collected',
      text: 'Claim tickets. One number is circled in green ink: <b>#13</b>. Nobody has collected it.' },
    'entrance:jacket': { cat: 'supply', note: 'Jacket #13: cash and a card, "K — Pier 9"',
      text: 'Ticket #13\'s leather jacket. Something heavy in the pocket: a roll of cash and a card that says only <b>"K — Pier 9"</b>.' },
    'entrance:list': { cat: 'deal', note: 'Guest list: "Moe — all night, all rooms"',
      text: 'The guest list. Half the names are crossed out. One is underlined twice: <b>"Moe — all night, all rooms."</b>' },
    'entrance:mints': { cat: 'deal', note: 'Super Squirt pressed to look like mints',
      text: 'A bowl of mints. A few are green and glitter under the light: Super Squirt, pressed to look like candy.' },
    'entrance:band': { item: 'VIP wristband', flavour: true, note: 'A spare VIP wristband',
      text: 'A spare <b>VIP wristband</b>, left on the counter. Nobody will miss it.' },

    'main:phone': { cat: 'drop', note: 'DJ\'s phone: a map pin on Pier 9',
      text: 'The DJ\'s phone, propped on the mixer: a map pin on the docks. <b>Pier 9.</b>' },
    'main:setlist': { cat: 'deal', note: 'Set list: "Shadow Walk" at 2 AM, when the back room opens',
      text: 'The set list. One track circled in red: <b>"Shadow Walk"</b>. The DJ plays it every night at 2 AM, right before the back room opens.' },
    'main:vial': { drink: true, flavour: true, note: 'A vial of pure Super Squirt in the booth',
      text: 'A tiny glowing green vial tucked behind the mixer. Pure <b>Super Squirt</b>, uncut.' },
    'main:mixer': { cat: 'deal', note: 'Green residue on the DJ\'s mixer',
      text: 'The mixer\'s faders are sticky with green residue. Whoever runs this booth handles the product.' },
    'main:headphones': { cat: 'deal', note: 'The DJ\'s headphones say "MOE"',
      text: 'Headphones with a name scratched into the band: <b>"MOE"</b>.' },

    'vip:tray': { cat: 'deal', note: 'Green powder on the VIP tray',
      text: 'A silver tray dusted with glittering green powder. Super Squirt before it\'s mixed into the shots.' },
    'vip:glass': { flavour: true, note: 'A lipstick glass, left in a hurry',
      text: 'A glass with a lipstick print. Someone left in a hurry when the doors opened.' },
    'vip:card': { cat: 'supply', note: 'Kraken Shipping, Pier 9: "K" again',
      text: 'A business card with a tall ship: <b>Kraken Shipping, Pier 9</b>. "K" again.' },
    'vip:watch': { cat: 'supply', note: 'Watch stopped at 2:00: "To Moe, from K."',
      text: 'An expensive watch, stopped at 2:00. Engraved on the back: <b>"To Moe, from K."</b>' },
    'vip:matches': { cat: 'drop', note: 'Bayside Motel matchbook, room 9',
      text: 'A matchbook from the <b>Bayside Motel</b>. Room 9 is written inside the cover.' },
    'vip:bucket': { flavour: true, note: 'The VIP table runs on drug money',
      text: 'The champagne is real. The money behind it isn\'t. This table runs on Super Squirt.' },

    'restroom:mirror': { flavour: true, note: 'A lipstick number on the mirror',
      text: 'A number in lipstick on the cracked mirror, half wiped off. A phone number, or a pier.' },
    'restroom:pills': { cat: 'deal', note: 'The restroom drop point, behind the towels',
      text: 'A zip bag of glowing green pills stuck behind the towel holder. This is the drop point.' },
    'restroom:towels': { flavour: true, note: 'A hollow behind the towel holder',
      text: 'The towel holder\'s cover is loose. A hollow space behind it, just the size of a bag.' },
    'restroom:receipt': { cat: 'deal', note: 'Receipt: 40 "house specials" at 1:58 AM',
      text: 'A crumpled receipt: forty shots of the "house special", paid in cash, 1:58 AM.' },
    'restroom:soap': { flavour: true, note: 'Green powder washed off at the sink',
      text: 'The soap smells faintly of something sweet and chemical. Someone washed their hands of green powder here.' },

    'office:ledger': { cat: 'deal', note: 'Ledger: an "SS" column, ten times the bar takings',
      text: 'The ledger: two sets of numbers. Drinks on the left, and on the right a column headed <b>"SS"</b>, ten times bigger.' },
    'office:cash': { cat: 'supply', note: 'Cash banded "K — Thursday"',
      text: 'A brick of cash with a band marked <b>"K — Thursday"</b>.' },
    'office:phone': { cat: 'supply', note: 'Burner: "Usual drop. Don\'t be late again, Moe."',
      text: 'A burner phone. One contact: <b>K</b>. Last message: "Usual drop. Don\'t be late again, Moe."' },
    'office:key': { item: 'cellar key', flavour: true, note: 'The cellar key',
      text: 'A key on a red tag: <b>CELLAR</b>. You take it.' },
    'office:photo': { cat: 'drop', note: 'A photo of Pier 9 at night',
      text: 'A framed photo of the pier at night. Pier 9.' },
    'office:monitor': { flavour: true, note: 'The 2 AM security footage was erased',
      text: 'The security feed shows the back hallway. The 2 AM recording has been erased.' },
    // the 3D club's own sources (v3)
    'talk:pushers': { v3: true, cat: 'deal', note: 'Overheard: Moe moved forty shots before midnight; K wants double by Thursday',
      text: '"Moe moved forty shots before midnight." "K wants double by Thursday. Says the boat won\'t wait."' },
    'talk:crew': { v3: true, cat: 'supply', note: 'Overheard: Rico takes K\'s delivery details in the VIP',
      text: '"Rico\'s got the delivery details from K. He keeps them in his head, up in VIP." "And Lenny wants the hero on camera if she shows."' },
    'talk:girls': { v3: true, cat: 'deal', note: 'Overheard: the green shot makes writing glow by the storage door',
      text: '"I did one green shot and the walls lit up. There\'s writing by the storage door, you can only see it high." "That\'s the stock code, idiot. Moe writes it in UV."' },
    'vip:host': { v3: true, cat: 'drop', note: 'Rico bragged: K\'s boat docks Thursday at Pier 9',
      text: 'Rico leans back, pleased with himself: <b>"K\'s boat docks Thursday, Pier 9. Moe sells it off the decks. Everybody wins."</b>' },
    'alley:bag': { v3: true, cat: 'supply', note: 'The courier\'s bag: vials stamped with a kraken',
      text: 'The courier\'s bag is full of glowing vials, every cap stamped with a little <b>kraken</b>.' },
    'restroom:deal': { v3: true, cat: 'deal', note: 'The stall dealer\'s phone: "Moe: refill at 2 AM"',
      text: 'The dealer\'s phone, still lit: <b>"Moe: refill at 2 AM. Same stall."</b>' },
    'storage:stash': { v3: true, cat: 'supply', note: 'Crates stamped KRAKEN SHIPPING, full of Super Squirt',
      text: 'Behind the beer crates: three cases stamped <b>KRAKEN SHIPPING</b>, packed with glowing green vials.' },
    'bar:spiked': { v3: true, cat: 'deal', note: 'A "house special" spiked with green powder',
      text: 'X-ray shows a cloud of glittering powder settling in the glass. The "house special" is spiked: Super Squirt, served at the bar.' },
    'uv:wall': { v3: true, cat: 'drop', note: 'UV writing: "SS to PIER 9, THU"',
      text: 'Under the drug-vision glow the wall is covered in UV marker: the stock code, and <b>"SS → PIER 9 · THU"</b>.' },
    'boss:confession': { v3: true, cat: 'drop', note: 'Lenny Gold confessed: the club launders it, Moe sells it, K ships it',
      text: 'Lenny folds: the club launders the money, Moe sells it off the decks, and K\'s boat brings it in at Pier 9 on Thursday.' },
  },
  // ---- the 3D club (v3): Talkers, the crowd's rumours, the VIP host, the owner
  solvedText: 'Moe deals it, "K" supplies it, and the next drop is Thursday at Pier 9.',
  drugName: 'Super Squirt', uvLine: 'SS > PIER 9 THU',
  carrierLine: 'Kraken-stamped cap: the crowd\'s being supplied right here.',
  talks: [
    { id: 'pushers', who: 'Two dealers', clue: 'talk:pushers' },
    { id: 'crew', who: 'Two of the crew', clue: 'talk:crew' },
    { id: 'girls', who: 'Two clubbers', clue: 'talk:girls' },
  ],
  // tap one in the crowd to note it; `teach` marks a VIP answer as learned
  rumours: [
    { id: 'rico', text: 'Rico in VIP only lets in people K sends.', teach: 'who' },
    { id: 'song', text: 'The DJ plays "Shadow Walk" right before the back room opens.', teach: 'word' },
    { id: 'boat', text: 'The good stuff comes in by boat. Pier something.', teach: 'where' },
    { id: 'glow', text: 'One green shot and the walls start glowing. Like, writing on them.' },
    { id: 'swap', text: 'Bouncers lose it at the drop. Staff door\'s wide open for a beat.' },
    { id: 'cams', text: 'Lenny\'s got a camera in every room. Even the restroom.' },
    { id: 'alley', text: 'There\'s a courier who smokes in the alley. Always carrying a bag.' },
    { id: 'ladies', text: 'Don\'t use the last stall in the restroom. Business only.' },
  ],
  // only with super-hearing on
  whispers: [
    { id: 'pass', text: 'Password\'s "Shadow Walk". Tell Rico K sent you.', teach: 'word' },
    { id: 'pier', text: 'Thursday. Pier 9. K\'s boat.', teach: 'where' },
    { id: 'code', text: 'Office code\'s {CODE}. Don\'t tell Lenny I told you.', code: true },
    { id: 'stash', text: 'Rest of it\'s behind the beer crates in storage.' },
  ],
  vip: {
    host: 'Rico "Velvet" Vance',
    intro: '"Well, look who wandered in. Sit. Prove you belong here, and maybe we talk."',
    questions: [
      { id: 'who', q: '"Who sent you?"', answer: 'k',
        options: [{ label: '"Moe sent me."', value: 'moe' }, { label: '"K sent me."', value: 'k' }, { label: '"The bartender."', value: 'bar' }, { label: '"Nobody. I\'m a fan."', value: 'fan' }] },
      { id: 'word', q: '"What\'s the word tonight?"', answer: 'shadow',
        options: [{ label: '"Green light."', value: 'green' }, { label: '"Kryptonite."', value: 'kr' }, { label: '"Shadow Walk."', value: 'shadow' }, { label: '"Pier nine."', value: 'pier' }] },
      { id: 'where', q: '"So where does the good stuff come in?"', answer: 'pier',
        options: [{ label: '"The cellar."', value: 'cellar' }, { label: '"Pier 9."', value: 'pier' }, { label: '"The Bayside Motel."', value: 'motel' }, { label: '"Through the restroom."', value: 'rest' }] },
    ],
    win: 'vip:host',
  },
  boss: {
    name: 'Lenny Gold',
    steps: [
      { cat: 'deal', line: '"I run a nightclub, sweetheart. People bring things in. That\'s not on me."' },
      { cat: 'supply', line: '"Moe? Kid works alone. Never heard of any K."' },
      { cat: 'drop', line: '"Even if you were right, you\'ll never catch the next shipment."' },
    ],
    confession: 'boss:confession',
  },
  questions: [
    { q: 'Who is pushing Super Squirt inside the club?', answer: 'moe',
      options: [{ label: 'The bartender', value: 'bar' }, { label: 'Moe, the DJ', value: 'moe' }, { label: 'The coat-check girl', value: 'coat' }, { label: 'The bouncer', value: 'door' }] },
    { q: 'Who supplies him?', answer: 'k',
      options: [{ label: 'The club\'s owner', value: 'owner' }, { label: 'A street gang', value: 'gang' }, { label: '"K", of Kraken Shipping', value: 'k' }, { label: 'The Bayside Motel manager', value: 'motel' }] },
    { q: 'When and where is the next drop?', answer: 'pier',
      options: [{ label: 'Tonight, in the cellar', value: 'cellar' }, { label: '2 AM, the restroom', value: 'rest' }, { label: 'Friday, the Bayside Motel', value: 'fri' }, { label: 'Thursday, Pier 9', value: 'pier' }] },
  ],
  // distribution points unlocked on the map by a solved case: each one whose clues were found
  leads: [
    { id: 'squirt-pier9', name: 'Super Squirt drop: Pier 9', kind: 'special', venue: 'Warehouse', theme: 'drugs', reward: 120,
      by: ['entrance:jacket', 'main:phone', 'vip:card', 'office:photo'],
      blurb: 'Thursday\'s Super Squirt shipment comes in at Pier 9. Shut it down.' },
    { id: 'squirt-kraken', name: 'Kraken Shipping warehouse', kind: 'special', venue: 'Warehouse', theme: 'drugs', reward: 100,
      by: ['bar:phone', 'vip:watch', 'office:cash', 'office:phone'],
      blurb: '"K" runs Super Squirt out of the Kraken Shipping warehouse. Raid it.' },
    { id: 'squirt-motel', name: 'Bayside Motel, room 9', kind: 'street', reward: 80,
      by: ['vip:matches'],
      blurb: 'Moe\'s crew cuts the drug in room 9 of the Bayside Motel. Bust it.' },
  ],
};
